### PR TITLE
Helper script to install all packages

### PR DESCRIPTION
**Pull request by Tirokk**
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-11-15T17:02:22Z" title="Friday, November 15th 2019, 6:02:22 pm +01:00">Nov 15, 2019</time>_
_Merged <time datetime="2019-11-18T10:27:27Z" title="Monday, November 18th 2019, 11:27:27 am +01:00">Nov 18, 2019</time>_
---

### Issues

- None

### Todo

- [X] None

### CODE REVIEW

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-11-15T17:51:01Z" title="Friday, November 15th 2019, 6:51:01 pm +01:00">Nov 15, 2019</time>_

---


Ignore the cypress test result, seems when I ran cypress locally, that made it believe that I'm the build server.

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2019-11-15T19:15:08Z" title="Friday, November 15th 2019, 8:15:08 pm +01:00">Nov 15, 2019</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/#/projects/qa7fe2/runs/2145/specs"></a> <b title="Passed">0</b>  &bull; <a href="https://dashboard.cypress.io/#/projects/qa7fe2/runs/2145/failures"></a> <b title="Failed">2</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Failed |
| **Commit** | ba450a4f98 |
| **Started** | Nov 15, 2019 5:08 PM |
| **Ended** | Nov 15, 2019 7:15 PM |
| **Duration** | 07:05 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Arch Linux -  |
| **Browser** | Chromium 78  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/#/projects/qa7fe2/runs/2145/specs)


---

### Failures

<table>
  <tbody>
    <tr>
        <th align="center">
          
        </th>
        <th align="left" colspan="2" style="width: 100%">
          cypress/integration/administration/TagsAndCategories.feature <a href="https://dashboard.cypress.io/#/projects/qa7fe2/runs/2145/failures">⏯</a>
        </th>
        <th align="right">
          2&nbsp;<a href="https://dashboard.cypress.io/#/projects/qa7fe2/runs/2145/failures">Failed</a>
        </th>
      </tr><tr>
        <td align="right">1</td>
        <td colspan="2">
          <a href="https://dashboard.cypress.io/#/projects/qa7fe2/runs/2145/failures/f7c32fb3-d9e3-4311-ae35-4cd8cd928fb2">          
            Tags and Categories > See an overview of categories</td>
          </a>
          <td> </td>
      </tr><tr>
        <td align="right">2</td>
        <td colspan="2">
          <a href="https://dashboard.cypress.io/#/projects/qa7fe2/runs/2145/failures/32c4163c-b222-41ac-a797-31cdbcf6428c">          
            Tags and Categories > See an overview of tags</td>
          </a>
          <td> </td>
      </tr>
  </tbody>
</table>


---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/#/projects/qa7fe2/settings)

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-11-18T15:05:10Z" title="Monday, November 18th 2019, 4:05:10 pm +01:00">Nov 18, 2019</time>_

---


it's cool that we have this, but for me it's much faster to install in parallel... can't you add a command to tell it to do that @roschaefer ??

**Review by Mogge — APPROVED** [review]
❤️ this!

**Pull request closed without merging**
