### PR TITLE
Fix failing build due to lorempixel.com being down

### LINKED ISSUE #883: 🐛 [Bug] Fix build
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-06-22T11:26:07Z" title="Saturday, June 22nd 2019, 1:26:07 pm +02:00">Jun 22, 2019</time>_
_Closed <time datetime="2019-06-24T19:22:12Z" title="Monday, June 24th 2019, 9:22:12 pm +02:00">Jun 24, 2019</time>_
---

## :bug: Bugreport

Our builds are failing with intermittent cypress test failures, I think cypress retries is not working
Attempt to revert it to a working state

Ended up being related to `faker` and it's use of `lorempixel`

### PR DESCRIPTION
**Pull request by Tirokk**
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-06-22T15:02:09Z" title="Saturday, June 22nd 2019, 5:02:09 pm +02:00">Jun 22, 2019</time>_
_Merged <time datetime="2019-06-24T19:22:11Z" title="Monday, June 24th 2019, 9:22:11 pm +02:00">Jun 24, 2019</time>_
---

### Issues

- fixes #883

### CODE REVIEW

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-06-24T14:30:55Z" title="Monday, June 24th 2019, 4:30:55 pm +02:00">Jun 24, 2019</time>_

---


running `docker-compose -f docker-compose.yml -f docker-compose.travis.yml up --build -d` locally and 
entering the container with `docker exec -it human-connection_backend_1 /bin/sh`, then navigating to `node_modules/faker/lib/image.js` shows that the changes not present in the latest published package are there. 

And it works locally with `Docker` as well
Screenshot at 2019-06-24 11:22:25


for some reason it is still failing the build with `TypeError: Cannot read property 'image' of undefined`
this appears to be coming from https://github.com/Human-Connection/Human-Connection/pull/885/files#diff-cd4d3ac61271d17c0d886dbd17e3a41eR16

we can see from `faker`'s unit tests, that this is how the method is supposed to be used https://github.com/Marak/faker.js/blob/master/test/image.unit.js#L111
and as noted it works locally, both with and without Docker

**Comment by Tirokk** [comment]
> [codecov[bot]](https://github.com/apps/codecov) **Authored by [codecov[bot]](https://github.com/apps/codecov)**
_<time datetime="2019-06-24T15:02:08Z" title="Monday, June 24th 2019, 5:02:08 pm +02:00">Jun 24, 2019</time>_

---


# [Codecov](https://codecov.io/gh/Human-Connection/Human-Connection/pull/885?src=pr&el=h1) Report
> :exclamation: No coverage uploaded for pull request base (`master@3c36cad`). [Click here to learn what that means](https://docs.codecov.io/docs/error-reference#section-missing-base-commit).
> The diff coverage is `n/a`.

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-06-24T19:42:05Z" title="Monday, June 24th 2019, 9:42:05 pm +02:00">Jun 24, 2019</time>_

---


thanks @Kachulio1 and @roschaefer 
feels great to get this merged :)

**Review by Mogge — APPROVED** [review]

**Review by Mogge — APPROVED** [review]
you have saved us

**Pull request closed without merging**
