### PR TITLE
Update DeleteData.vue

### PR DESCRIPTION
**Pull request by Tirokk**
> [erhardtstiefel](https://github.com/erhardtstiefel) **Authored by [erhardtstiefel](https://github.com/erhardtstiefel)**
_<time datetime="2019-12-07T16:16:26Z" title="Saturday, December 7th 2019, 5:16:26 pm +01:00">Dec 7, 2019</time>_
_Closed <time datetime="2019-12-11T11:41:01Z" title="Wednesday, December 11th 2019, 12:41:01 pm +01:00">Dec 11, 2019</time>_
---

## 🍰 Pullrequest

Removes two lines of checkboxes and counters from form in en.json
Bugfixes 01e

### Issues

- [X] None

### CODE REVIEW

**Comment by Tirokk** [comment]
> [erhardtstiefel](https://github.com/erhardtstiefel) **Authored by [erhardtstiefel](https://github.com/erhardtstiefel)**
_<time datetime="2019-12-07T16:17:39Z" title="Saturday, December 7th 2019, 5:17:39 pm +01:00">Dec 7, 2019</time>_

---


Must be merged together with Update en.json #2445

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2019-12-07T16:43:36Z" title="Saturday, December 7th 2019, 5:43:36 pm +01:00">Dec 7, 2019</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/2717/specs"></a> <b title="Passed">48</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/2717/failures"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | fcbbb25e7a |
| **Started** | Dec 7, 2019 4:33 PM |
| **Ended** | Dec 7, 2019 4:43 PM |
| **Duration** | 10:22 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Chromium 78  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/2717/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings)

**Comment by Tirokk** [comment]
> [erhardtstiefel](https://github.com/erhardtstiefel) **Authored by [erhardtstiefel](https://github.com/erhardtstiefel)**
_<time datetime="2019-12-11T11:41:01Z" title="Wednesday, December 11th 2019, 12:41:01 pm +01:00">Dec 11, 2019</time>_

---


After a longer discussion I understood just to change the title of the function deleteUserAccount by renaming "name": "Delete data", to "name": "Delete user account", for every language.json to solve the bug. Therefore this PR becomes obsolete. Sorry for the unneccessary reviews and tests.

**Review by Mogge — CHANGES_REQUESTED** [review]
Hey @erhardtstiefel thank you for the pull request!

Why did you remove the two check boxes for deleting posts and comments? Users can say they want their posts and comments to remain in the database even if their account has been deleted.

Screenshot - 2019-12-09T235152 271


Screenshot - 2019-12-09T235246 189


Screenshot - 2019-12-09T235436 201


There is frontend test that is now failing. The test expects the two check boxes to be present. :point_up:

**Review by Mogge — CHANGES_REQUESTED** [review]
really nice @erhardtstiefel !!
together with @roschaefer request, is there a way that you can add the changes in
https://github.com/Human-Connection/Human-Connection/pull/2445
https://github.com/Human-Connection/Human-Connection/pull/2448
https://github.com/Human-Connection/Human-Connection/pull/2449

to this `PR`, so that we can review and merge them together?

**Pull request closed without merging**
