### PR TITLE
Fix depreciation warnings

### PR DESCRIPTION
**Pull request by Tirokk**
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-08-02T22:07:52Z" title="Saturday, August 3rd 2019, 12:07:52 am +02:00">Aug 3, 2019</time>_
_Merged <time datetime="2019-08-06T14:39:30Z" title="Tuesday, August 6th 2019, 4:39:30 pm +02:00">Aug 6, 2019</time>_
---

I couldn't see any difference in using `transition`, `pageTransition` or
neither of those, so I decided to disable the configuration completely.

### Issues

- None

### Todo

- [X] None

### CODE REVIEW

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-08-06T06:46:16Z" title="Tuesday, August 6th 2019, 8:46:16 am +02:00">Aug 6, 2019</time>_

---


I have been unable to replicate this bug @roschaefer, are you on the latest code?
this duplicate key must not have something to do with the filterPosts by usersFollowed or byCategories because the duplicate key is a `post.id`, it seems.

I was able to see that if a user filters by categories and/or usersFollowed and then sort, all the posts are fetched instead of just the ones that a user had filtered for

**Review by Mogge — CHANGES_REQUESTED** [review]
Looks great, but when I do the following

1. Click the filter posts dropdown
2. Select only followed users
3. Click on logo or exit page - this resets the filters
5. The button for filter by followed users is still green

Apart from that: Really nice work!

nice work

**Review by Mogge — CHANGES_REQUESTED** [review]
Ok, so this looks better: When I click on e.g. a page and return, the button is not green anymore. However I found another bug:

2019-08-06-011012_1920x1080_scrot

**Review by Mogge — CHANGES_REQUESTED** [review]
Sorry Matt, but I found another bug..

2019-08-06-232701_1920x1080_scrot



shrug

**Review by Mogge — APPROVED** [review]
Amazing Dear !
I love to filter by the users I follow !!! @mattwr18 😍
Wonderful done. 🙏🏼 🚀

Elmer Sheep GIF

**Review by Mogge — APPROVED** [review]
Looks nice, I could think of one improvement for the future: Encode the filter params in the URL, similar to the hashtags. This has two advantages:
* You can send someone a link with a filtered set of posts
* You can redirect to `/` and the filters get automatically reset

Potentially you could also use lodash's deepmerge for updating the filters:
https://lodash.com/docs/4.17.15#merge

But that's for another day - great work!

good

**Pull request closed without merging**
