### PR TITLE
Edit post this.author error fix

### LINKED ISSUE #1310: 🐛 [Bug] Cannot edit post
> [alina-beck](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2019-08-20T17:25:35Z" title="Tuesday, August 20th 2019, 7:25:35 pm +02:00">Aug 20, 2019</time>_
_Closed <time datetime="2019-08-22T07:30:42Z" title="Thursday, August 22nd 2019, 9:30:42 am +02:00">Aug 22, 2019</time>_
---

## :bug: Bugreport
When I try to edit one of my posts the app crashes – with `this.author is undefined` (and a bunch of other console warnings on reloading the page).

### Steps to reproduce the behavior
1. Open one of the posts you created
2. In the menu on the top right click on `Edit Post`
3. Get redirected to `/post/edit` and see the app crash

### Expected behavior
The editor should be displayed so I can edit my post.

### Version & Environment
Type: [Desktop]
- OS: [macOS10.14.5]
- Browser: [Firefox]
- Version [68.0.2]
- Device: [MacbookPro]

### PR DESCRIPTION
**Pull request by Tirokk**
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-08-21T11:46:05Z" title="Wednesday, August 21st 2019, 1:46:05 pm +02:00">Aug 21, 2019</time>_
_Closed <time datetime="2019-08-22T07:30:19Z" title="Thursday, August 22nd 2019, 9:30:19 am +02:00">Aug 22, 2019</time>_
---

### Issues

- fixes #1310

### CODE REVIEW

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-08-22T09:36:16Z" title="Thursday, August 22nd 2019, 11:36:16 am +02:00">Aug 22, 2019</time>_

---


@mattwr18 no problem to make only the icon green. You would have a `<ds-button icon="filter" ghost primary>` then. Look here: https://styleguide.human-connection.org/navigation/dsbutton

I removed the `ghost` attribute on purpose when it's primary because I could hardly see the difference.

**Comment by Tirokk** [comment]
> [alina-beck](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2019-08-28T09:45:03Z" title="Wednesday, August 28th 2019, 11:45:03 am +02:00">Aug 28, 2019</time>_

---


@mattwr18 @roschaefer sorry I didn't respond earlier! I think what we could do – after the release – is display the active filters in the same place we display the active hashtag. Ideally with the possibility to disable all filters (or even single filters) right there. Would you like that?

**Comment by Tirokk** [comment]
> [appinteractive](https://github.com/appinteractive) **Authored by [appinteractive](https://github.com/appinteractive)**
_<time datetime="2019-08-29T08:51:35Z" title="Thursday, August 29th 2019, 10:51:35 am +02:00">Aug 29, 2019</time>_

---


@alina-beck do you mean in the search bar?

**Comment by Tirokk** [comment]
> [alina-beck](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2019-09-02T09:14:38Z" title="Monday, September 2nd 2019, 11:14:38 am +02:00">Sep 2, 2019</time>_

---


@appinteractive no, I mean in the one below – which only displays at the moment when filtering by hashtag:

Screenshot 2019-09-02 at 10 11 04

That is, _if_ we want to keep this at all. I definitely see some room for design improvements there. :smile:

**Comment by Tirokk** [comment]
> [appinteractive](https://github.com/appinteractive) **Authored by [appinteractive](https://github.com/appinteractive)**
_<time datetime="2019-09-02T10:53:00Z" title="Monday, September 2nd 2019, 12:53:00 pm +02:00">Sep 2, 2019</time>_

---


I don’t know if duplicating that stuff there makes sense here as it should be in the searchbar (at least the hashtag and the x button) at least the shadow has to die before it starts to look a bit better. The filter also may apply to other areas like the recommended section so it would anyway only make sense to show it in the topbar where it belongs. 

That’s just my humble opinion.

**Comment by Tirokk** [comment]
> [alina-beck](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2019-09-02T12:25:11Z" title="Monday, September 2nd 2019, 2:25:11 pm +02:00">Sep 2, 2019</time>_

---


I would prefer to have it in the topbar as well. The question then is how exactly this would look like and what to do when too many filters are active to display them side by side. Do you have a solution in mind already?

**Comment by Tirokk** [comment]
> [appinteractive](https://github.com/appinteractive) **Authored by [appinteractive](https://github.com/appinteractive)**
_<time datetime="2019-09-02T13:38:21Z" title="Monday, September 2nd 2019, 3:38:21 pm +02:00">Sep 2, 2019</time>_

---


Something like that?

grafik

**Comment by Tirokk** [comment]
> [appinteractive](https://github.com/appinteractive) **Authored by [appinteractive](https://github.com/appinteractive)**
_<time datetime="2019-09-02T16:11:09Z" title="Monday, September 2nd 2019, 6:11:09 pm +02:00">Sep 2, 2019</time>_

---


I think that functionality is already integrated to the input field that we use

**Comment by Tirokk** [comment]
> [alina-beck](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2019-09-03T08:30:54Z" title="Tuesday, September 3rd 2019, 10:30:54 am +02:00">Sep 3, 2019</time>_

---


For manual filters maybe, but not for the ones selected in the filter menu.

**Comment by Tirokk** [comment]
> [appinteractive](https://github.com/appinteractive) **Authored by [appinteractive](https://github.com/appinteractive)**
_<time datetime="2019-09-03T08:45:17Z" title="Tuesday, September 3rd 2019, 10:45:17 am +02:00">Sep 3, 2019</time>_

---


Okay then I don’t know that you are talking about.

**Comment by Tirokk** [comment]
> [alina-beck](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2019-09-03T09:09:25Z" title="Tuesday, September 3rd 2019, 11:09:25 am +02:00">Sep 3, 2019</time>_

---


I just checked – this is neither implemented in the current alpha nor nitro version of the app. The search just gives you a dropdown with corresponding posts (i.e. you can't just enter a search term and hit return) and the selected filters are only displayed in the filter menu. This is what I mean:

Screenshot 2019-09-03 at 10 03 00

As soon as you close the menu there is no way to tell which filters are currently selected. This whole PR was about showing the user that the content is filtered (which we now did by coloring the filter button green) but it would be even better to see _which_ filters are active. And I would very much like a solution similar to the one you proposed above to do this. 🙂

**Comment by Tirokk** [comment]
> [appinteractive](https://github.com/appinteractive) **Authored by [appinteractive](https://github.com/appinteractive)**
_<time datetime="2019-09-04T07:32:56Z" title="Wednesday, September 4th 2019, 9:32:56 am +02:00">Sep 4, 2019</time>_

---


I will push a repo with some stuff I experimenting with in the next days, there we could just try out different approaches before integrating them, if you are interested. 

I currently doing that for the comments (how to display reply’s) and the topbar (best ways for responsiveness)

**Review by Mogge — APPROVED** [review]
merging this for now cause it is an improvement, but maybe @alina-beck has an idea where we can both notice the difference between filters active and not, but also look nicer.

**Pull request closed without merging**
