### PR TITLE
🍰 release contribution again

### PR DESCRIPTION
**Pull request by Tirokk**
> [ogerly](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-06-04T14:33:32Z" title="Tuesday, June 4th 2019, 4:33:32 pm +02:00">Jun 4, 2019</time>_
_Merged <time datetime="2019-06-04T21:20:13Z" title="Tuesday, June 4th 2019, 11:20:13 pm +02:00">Jun 4, 2019</time>_
---

## 🍰 Pullrequest 

- [X] Beiträge können von deaktiviert zu aktiviert gesetzt werden.
- [X] Posts can be reenabled once disabled.

### Issues

- [X] fixes https://github.com/Human-Connection/Human-Connection/issues/432

### Checklist

- [X] None

### How2Test

- [X] None

### Todo

- [ ] location.reload() is not good way!! reload only the contribution element https://github.com/Human-Connection/Human-Connection/pull/738

### CODE REVIEW

**Comment by Tirokk** [comment]
> [ogerly](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-06-04T16:24:18Z" title="Tuesday, June 4th 2019, 6:24:18 pm +02:00">Jun 4, 2019</time>_

---


@roschaefer  yes this problem is @Tirokk and me well-known 
here the issue for this problem : https://github.com/Human-Connection/Human-Connection/issues/734

**Comment by Tirokk** [comment]
> [codecov[bot]](https://github.com/apps/codecov) **Authored by [codecov[bot]](https://github.com/apps/codecov)**
_<time datetime="2019-06-04T16:34:31Z" title="Tuesday, June 4th 2019, 6:34:31 pm +02:00">Jun 4, 2019</time>_

---


# [Codecov](https://codecov.io/gh/Human-Connection/Human-Connection/pull/736?src=pr&el=h1) Report
> Merging [#736](https://codecov.io/gh/Human-Connection/Human-Connection/pull/736?src=pr&el=desc) into [master](https://codecov.io/gh/Human-Connection/Human-Connection/commit/5aafe5d1b2bcc77a57362784a015273f03c499f0?src=pr&el=desc) will **increase** coverage by `0.59%`.
> The diff coverage is `76%`.

[Impacted file tree graph](https://codecov.io/gh/Human-Connection/Human-Connection/pull/736?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #736      +/-   ##
==========================================
+ Coverage   23.17%   23.76%   +0.59%     
==========================================
  Files         164      165       +1     
  Lines        2300     2323      +23     
  Branches      119      120       +1     
==========================================
+ Hits          533      552      +19     
- Misses       1732     1736       +4     
  Partials       35       35
```


| [Impacted Files](https://codecov.io/gh/Human-Connection/Human-Connection/pull/736?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [webapp/components/ContentMenu.vue](https://codecov.io/gh/Human-Connection/Human-Connection/pull/736/diff?src=pr&el=tree#diff-d2ViYXBwL2NvbXBvbmVudHMvQ29udGVudE1lbnUudnVl) | `32.14% <0%> (-3.86%)` | :arrow_down: |
| [webapp/components/Modal/DisableModal.vue](https://codecov.io/gh/Human-Connection/Human-Connection/pull/736/diff?src=pr&el=tree#diff-d2ViYXBwL2NvbXBvbmVudHMvTW9kYWwvRGlzYWJsZU1vZGFsLnZ1ZQ==) | `85.71% <100%> (+1.5%)` | :arrow_up: |
| [webapp/components/Modal.vue](https://codecov.io/gh/Human-Connection/Human-Connection/pull/736/diff?src=pr&el=tree#diff-d2ViYXBwL2NvbXBvbmVudHMvTW9kYWwudnVl) | `78.57% <100%> (+1.65%)` | :arrow_up: |
| [webapp/components/ReleaseModal/ReleaseModal.vue](https://codecov.io/gh/Human-Connection/Human-Connection/pull/736/diff?src=pr&el=tree#diff-d2ViYXBwL2NvbXBvbmVudHMvUmVsZWFzZU1vZGFsL1JlbGVhc2VNb2RhbC52dWU=) | `94.12% <94.12%> (ø)` | |

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-06-04T19:34:34Z" title="Tuesday, June 4th 2019, 9:34:34 pm +02:00">Jun 4, 2019</time>_

---


hey @roschaefer thanks for uploading the `gif`

I pulled it down and we are still dealing with the `console.error` issue @ogerly 
Screenshot at 2019-06-04 16:32:45


I'll have a look and see if I can figure it out... other than that it looks good and I'd love to merge!!

**Comment by Tirokk** [comment]
> [ogerly](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-06-04T22:25:35Z" title="Wednesday, June 5th 2019, 12:25:35 am +02:00">Jun 5, 2019</time>_

---


TODO: here: https://github.com/Human-Connection/Human-Connection/pull/738

**Review by Mogge — APPROVED** [review]
Looks good to me!

looks good to me


I quickly pulled down your code and tried it out. I added one extra commit to improve UX.

There is some strange behaviour if you disable a post, but I don't think this is related to your PR:

out2

For some reason, I seee a graphql error message that I'm not authorised to do this, soon followed by a success message.

**Pull request closed without merging**
