### PR TITLE
🍰 2119-Fix Contribution  consistent form input validation

### LINKED ISSUE #2119: 🚀 [Feature] Create Post – consistent form input validation
> [alina-beck](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2019-11-05T08:10:42Z" title="Tuesday, November 5th 2019, 9:10:42 am +01:00">Nov 5, 2019</time>_
_Closed <time datetime="2019-11-18T23:27:48Z" title="Tuesday, November 19th 2019, 12:27:48 am +01:00">Nov 19, 2019</time>_
---

## :rocket: Feature
Validate all fields of the `create post` form in a consistent way. (Ideally, the same system can then be applied to all forms on the network.)

Screenshot 2019-11-05 at 10 44 14

### User Problem
It is unclear which parts of the `create post` form are required and what kind of input is valid. Many users don't know that they have to select `categories` or that a video by itself is not enough content (see #1876).

### Implementation
I would like it if the `title` field and the main `content` editor could be validated with visible feedback _after_ the user entered their input and left the field (i.e. onBlur). Validating input too early (when the user just started typing) or too late (when the user tried to save the post) can lead to frustration.

Open questions / challenges:
- Since images are optional they probably don't need validation?
- It is unclear if the third-party editor allows for the behavior proposed above
- We need a clear message to explain to users that the length of the URL of an embed link does not count toward the minimum content length
- We need to come up with a solution for `categories`
- Is the `language` required? Should it be pre-filled?
- In addition to the validation (after user input) we could also mark required fields (before user input) – but how?

### Design & Layout
The visual feedback for `title` and `content` could look like this:
Screenshot 2019-11-05 at 10 52 39

Question: Do we also want to give feedback for valid content (e.g. a green border and a checkmark)?

### Validation (How can we make sure that this feature solves the above problem?)
- no more bug reports about videos as posts not being accepted
- we could measure if users are faster when creating posts (are any analytics tools set up?)
- developers can see if new contributors are less confused when creating a post in a pairing session

### PR DESCRIPTION
**Pull request by Tirokk**
> [ogerly](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-11-07T08:14:54Z" title="Thursday, November 7th 2019, 9:14:54 am +01:00">Nov 7, 2019</time>_
_Merged <time datetime="2019-11-18T23:27:48Z" title="Tuesday, November 19th 2019, 12:27:48 am +01:00">Nov 19, 2019</time>_
---

## 🍰 Pullrequest
Fix consistent form input validation

 
 
ezgif com-video-to-gif (2)

# Behaviour 1
FireShot Capture 188 - Human Connection - Human Connection - localhost

# Behaviour 2
FireShot Capture 187 - Human Connection - Human Connection - localhost

# Behaviour 3
FireShot Capture 186 - Human Connection - Human Connection - localhost

### Issues
- fixes #2119

### CODE REVIEW

**Comment by Tirokk** [comment]
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2019-11-07T15:03:29Z" title="Thursday, November 7th 2019, 4:03:29 pm +01:00">Nov 7, 2019</time>_

---


Hey, chick @ogerly ,
I will make a review tomorrow morning.

Cool with the red triangles !!! 😎

The only thing I say right away to the design is:
I would only make left align of the language menu and not a right align.
This is much to wide.
What you say?

**Comment by Tirokk** [comment]
> [ogerly](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-11-07T15:17:20Z" title="Thursday, November 7th 2019, 4:17:20 pm +01:00">Nov 7, 2019</time>_

---


@Tirokk  I pulled the select bar over the whole box so it comes across better. 
on mobile largest it also runs over the whole box. and the importance is even more clear. 
i can do it left justified and 50% flex
i needed it a bit bigger because of the german text that was broken in the beginning and stood over

**Comment by Tirokk** [comment]
> [ogerly](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-11-11T10:54:32Z" title="Monday, November 11th 2019, 11:54:32 am +01:00">Nov 11, 2019</time>_

---


this PR is closed and here it goes on https://github.com/Human-Connection/Human-Connection/pull/2189

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2019-11-18T23:26:06Z" title="Tuesday, November 19th 2019, 12:26:06 am +01:00">Nov 19, 2019</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/#/projects/qa7fe2/runs/2161/specs"></a> <b title="Passed">48</b>  &bull; <a href="https://dashboard.cypress.io/#/projects/qa7fe2/runs/2161/failures"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | 9864532189 |
| **Started** | Nov 18, 2019 11:13 PM |
| **Ended** | Nov 18, 2019 11:26 PM |
| **Duration** | 13:01 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Chromium 78  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/#/projects/qa7fe2/runs/2161/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/#/projects/qa7fe2/settings)

**Review by Mogge — APPROVED** [review]
Looks good to me now! Great teamwork!

great teamwork

**Pull request closed without merging**
