### PR TITLE
Update fetchMore functionality on profile page

### LINKED ISSUE #2011: 🐛 [Bug]Load more broken on profile page
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-10-23T07:35:06Z" title="Wednesday, October 23rd 2019, 9:35:06 am +02:00">Oct 23, 2019</time>_
_Closed <time datetime="2019-10-23T09:23:02Z" title="Wednesday, October 23rd 2019, 11:23:02 am +02:00">Oct 23, 2019</time>_
---

## :bug: Bugreport

This was reported by a User:
Habe mich scheinbar zu früh gefreut :(. Seit heute bzw. nach den HC-Wartungsarbeiten zeigt mir mein HC-Profil nun nur noch 5 Beiträge (von ehemals 13) an. Einen mit der Überschrift "UNAVAILABLE". Und die Restlichen fehlen nun ganz. Unglücklicher Weise fehlt nun u.a. auch der "HC-INFO-GUIDE für neue User". Und die "mehr laden"-Funktion (über den Pfeil nach unten) funktioniert überhaupt nicht mehr bzw. wird vom System nicht ausgeführt. Das erschwert die ständige Aktualisierung bzw. macht diese derzeit unmöglich. Zur Not habe ich zwar noch textliche Sicherungs-Kopien, – aber hinsichtlich des geplanten öffentlich Gehens kein besonders beruhigender bzw. professioneller Zustand. Könnt Ihr mal die Ursache heraus finden bzw. sehen, ob das erneut nur die Darstellung in meinem Profil ist, oder ob sich da ein weiterer "Bug" eingeschlichen hat, bzw. wie dieses erneut behoben werden kann?! Zumal nun immer mehr neue User (u.a. ja auch bei den Online-HC-Teamtreffen) und hier vermehrt nach HC-Infos fragen, die fast alle im Guide beantwortet werden.

Würd' mich freuen (bzw. es würde mir die ehrenamtliche Arbeit erleichtern)! In diesem Sinne: LG @ all 🤗❤️

Apparently I was happy too early :(. Since today resp. after the HC maintenance work my HC profile now shows me only 5 posts (from former 13). One with the title "UNAVAILABLE". And the rest are missing now. Unfortunately the "HC-INFO-GUIDE for new users" is missing now. And the "load more" function (using the down arrow) no longer works or is not executed by the system. This makes the constant updating more difficult or impossible at the moment. I still have text backup copies in case of need - but not a particularly calming or professional state with regard to the planned public walking. Can you find out the reason or see if this is just the display in my profile again, or if another "bug" has crept in or how to fix it again? Especially now that more and more new users are asking for HC information (e.g. at the online HC team meetings), almost all of which are answered in the guide.

I would be happy (or it would make my voluntary work easier)! In this sense: LG @ all 🤗❤️

Translated with www.DeepL.com/Translator
### Steps to reproduce the behavior
1. go to someone's profile page that has more than 6 posts
2. click load more
3. see that it does not show the new posts
4. ...
5. Profit

### Version & Environment
 Type: []      
 - OS: []      
 - Browser: [] 
 - Version []  
 - Device: []

### PR DESCRIPTION
**Pull request by Tirokk**
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-10-23T07:43:44Z" title="Wednesday, October 23rd 2019, 9:43:44 am +02:00">Oct 23, 2019</time>_
_Merged <time datetime="2019-10-23T09:23:02Z" title="Wednesday, October 23rd 2019, 11:23:02 am +02:00">Oct 23, 2019</time>_
---

- clean up from pinned Posts PR

### Issues

- fixes #2011 

### Todo

- [X] None

### CODE REVIEW

**Comment by Tirokk** [comment]
> [alina-beck](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2019-10-23T08:41:54Z" title="Wednesday, October 23rd 2019, 10:41:54 am +02:00">Oct 23, 2019</time>_

---


it works! 💚 😍 🎉 
now somebody needs to tell `Travis`... 😜

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-10-23T08:46:07Z" title="Wednesday, October 23rd 2019, 10:46:07 am +02:00">Oct 23, 2019</time>_

---


hahah @alina-beck it might have broken something else
this is why it is risky without e2e tests because this should have failed the build the first time, but we have big holes in our test coverage

**Comment by Tirokk** [comment]
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2019-10-23T08:57:10Z" title="Wednesday, October 23rd 2019, 10:57:10 am +02:00">Oct 23, 2019</time>_

---


That is the danger if we just have a look on the changed lines in a PR. :grimacing: @mattwr18 @alina-beck

**Review by Mogge — APPROVED** [review]
Yeah, I had the hope that you will be able to find it very quick! 📌👍🏼
Thanks @mattwr18 

I approved without successful builds, because of the hurry …

PS: I already restarted the branch build that was failing, because of a Cypress timeout error …

**Review by Mogge — APPROVED** [review]

**Pull request closed without merging**
