### PR TITLE
Set up editor placeholder to use Vuex

### LINKED ISSUE #835: 🐛 [Bug] Use Vuex to make editor placeholder reactive
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-06-15T16:07:32Z" title="Saturday, June 15th 2019, 6:07:32 pm +02:00">Jun 15, 2019</time>_
_Closed <time datetime="2019-06-19T12:59:18Z" title="Wednesday, June 19th 2019, 2:59:18 pm +02:00">Jun 19, 2019</time>_
---

## :bug: Bugreport

Currently, we have a hack where we do a `$root.$emit` to change the placeholder text.
We want to avoid these event listeners in the code base, one way we can do that is using Vuex.

### PR DESCRIPTION
**Pull request by Tirokk**
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-06-15T18:27:46Z" title="Saturday, June 15th 2019, 8:27:46 pm +02:00">Jun 15, 2019</time>_
_Merged <time datetime="2019-06-19T12:59:18Z" title="Wednesday, June 19th 2019, 2:59:18 pm +02:00">Jun 19, 2019</time>_
---

- to make reactive
- safer than using global event buses ($root.$emit)

Co-authored-by: Wolfgang Huß <wolle.huss@pjannto.com>
Co-authored-by: Mike Aono <aonomike@gmail.com>

### Issues

- fixes #835 

We did this `PR` as part of the new `VueJS Mob` pair programming session, `Saturdays 3pm UTC`

### CODE REVIEW

**Comment by Tirokk** [comment]
> [codecov[bot]](https://github.com/apps/codecov) **Authored by [codecov[bot]](https://github.com/apps/codecov)**
_<time datetime="2019-06-17T13:08:29Z" title="Monday, June 17th 2019, 3:08:29 pm +02:00">Jun 17, 2019</time>_

---


# [Codecov](https://codecov.io/gh/Human-Connection/Human-Connection/pull/836?src=pr&el=h1) Report
> :exclamation: No coverage uploaded for pull request base (`master@53ce729`). [Click here to learn what that means](https://docs.codecov.io/docs/error-reference#section-missing-base-commit).
> The diff coverage is `n/a`.

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-06-17T21:11:24Z" title="Monday, June 17th 2019, 11:11:24 pm +02:00">Jun 17, 2019</time>_

---


 thanks @Tirokk 
@roschaefer I wrote a component test for `LocaleSwitch`, but I wanted to add a test that the `editor/SET_PLACEHOLDER_TEXT` is called when a user changes the locale, but I can't check that it's called unless it's a mock or a spy...
If I set it up as a mock, I get this console.error `[vuex] unknown mutation type: editor/SET_PLACEHOLDER_TEXT`

I could get rid of this error by importing the mutations from `editor/SET_PLACEHOLDER_TEXT`, but then I can't check to see that it's called.

Maybe, it's something simple, but it's not obvious to me, so I thought I'd work on something else and see what others thought... this `PR` has been approved and I think ups the test coverage, so maybe we merge, but I thought I'd check to see what you think...

**Review by Mogge — APPROVED** [review]
Hey, good made buddy !!! 💫
Glad, that you had the idea of this solution …

Great to work together with you 😍

Dogs roll

**Review by Mogge — APPROVED** [review]

**Review by Mogge — APPROVED** [review]
Thanks for the additional tests @mattwr18 !!!
😁👋🏼

**Pull request closed without merging**
