### PR TITLE
[Systems-Development-and-Frameworks] Clickable hashtags

### LINKED ISSUE #1851: 🚀 [Feature] Make Tags below Posts  clickable as Hashtags are
> [datenbrei](https://github.com/datenbrei) **Authored by [datenbrei](https://github.com/datenbrei)**
_<time datetime="2019-10-09T10:36:14Z" title="Wednesday, October 9th 2019, 12:36:14 pm +02:00">Oct 9, 2019</time>_
_Closed <time datetime="2019-11-06T15:20:43Z" title="Wednesday, November 6th 2019, 4:20:43 pm +01:00">Nov 6, 2019</time>_
---

## :rocket: Feature
You can click on a hashtag, but not on the tags below the post, which are made out of them.

Also the **Tag below should be clickable, as the hashtag is**.

### Design & Layout
tags

### Additional context

Bildschirmfoto 2019-10-25 um 22 03 29

Should have links like here:

Bildschirmfoto 2019-10-26 um 09 43 55

### PR DESCRIPTION
**Pull request by Tirokk**
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-10-29T16:38:52Z" title="Tuesday, October 29th 2019, 5:38:52 pm +01:00">Oct 29, 2019</time>_
_Merged <time datetime="2019-11-19T13:00:29Z" title="Tuesday, November 19th 2019, 2:00:29 pm +01:00">Nov 19, 2019</time>_
---

## 🍰 Pullrequest

Screenshot - 2019-10-29T174112 718

### Issues

- fix #1851 

### Todo

- [x] Figure out the URL pattern to search for posts with a specific hashtag
- [x] Use `<nuxt-link>` to generate a link according to the URL schema

### CODE REVIEW

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-11-18T21:55:05Z" title="Monday, November 18th 2019, 10:55:05 pm +01:00">Nov 18, 2019</time>_

---


Screenshot - 2019-11-18T225502 987

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2019-11-19T01:15:29Z" title="Tuesday, November 19th 2019, 2:15:29 am +01:00">Nov 19, 2019</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/#/projects/qa7fe2/runs/2169/specs"></a> <b title="Passed">48</b>  &bull; <a href="https://dashboard.cypress.io/#/projects/qa7fe2/runs/2169/failures"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | abb3849a69 |
| **Started** | Nov 19, 2019 1:01 AM |
| **Ended** | Nov 19, 2019 1:15 AM |
| **Duration** | 13:40 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Chromium 78  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/#/projects/qa7fe2/runs/2169/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/#/projects/qa7fe2/settings)

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-11-19T13:10:31Z" title="Tuesday, November 19th 2019, 2:10:31 pm +01:00">Nov 19, 2019</time>_

---


@mattwr18 nope. One student worked on the issue but probably forgot to upload the commits

**Review by Mogge — APPROVED** [review]
great job @roschaefer!! did your students help on this one, in the end?

**Pull request closed without merging**
