### PR TITLE
[WIP] Frontend implementation for notifications

### PR DESCRIPTION
**Pull request by Tirokk**
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-04-08T12:54:37Z" title="Monday, April 8th 2019, 2:54:37 pm +02:00">Apr 8, 2019</time>_
_Merged <time datetime="2019-04-18T16:50:13Z" title="Thursday, April 18th 2019, 6:50:13 pm +02:00">Apr 18, 2019</time>_
---

### Issues
- [X] fixes: #347
- [X] fixes: #348 

### Checklist

- [X] None

### How2Test

- [X] None

### Todo

- [x] Shall we re-use `PostCard.vue` in `Notification.vue`?
- [x] Write a cucumber test to mark a notification as read

### CODE REVIEW

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-04-10T00:43:10Z" title="Wednesday, April 10th 2019, 2:43:10 am +02:00">Apr 10, 2019</time>_

---


on the root path `/`
Screenshot at 2019-04-09 21:25:16
on a post `/post/<id>/<slug>`
Screenshot at 2019-04-09 21:27:58
on a user's profile, it looks the same as on the root path

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-04-10T09:38:32Z" title="Wednesday, April 10th 2019, 11:38:32 am +02:00">Apr 10, 2019</time>_

---


@mattwr18 I saw that already. I believe this is a bug on the `PostCard.vue`. Apparently its CSS depends on where you render the component, which is bad.

@mattwr18 question is: Do we actually want to re-use `PostCard.vue` here?

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-04-10T12:18:32Z" title="Wednesday, April 10th 2019, 2:18:32 pm +02:00">Apr 10, 2019</time>_

---


> @mattwr18 I saw that already. I believe this is a bug on the `PostCard.vue`. Apparently its CSS depends on where you render the component, which is bad.
> 
> @mattwr18 question is: Do we actually want to re-use `PostCard.vue` here?

I didn't upload the photos cause I thought you might not have seen, it was more to help other people understand the issue that we ran into. 
Maybe not? If it is making it tricky to style it, maybe it would be easier to create our own component?

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-04-16T01:30:06Z" title="Tuesday, April 16th 2019, 3:30:06 am +02:00">Apr 16, 2019</time>_

---


Extracted the `NotificationsPostCard` into its own component to be able to style better
Screenshot at 2019-04-15 19:27:05

It also seemed quite wide to me, so I added a `max-width`, which looks better on mobile in my opinion.. here are some screen shots, what do you all think?
without max-width:
Screenshot at 2019-04-15 19:27:25
with:
Screenshot at 2019-04-15 19:25:32
with max-width wide screen:
Screenshot at 2019-04-15 19:25:53

**Review by Mogge — APPROVED** [review]

**Pull request closed without merging**
