### PR TITLE
Add test coverage

### LINKED ISSUE #469: 🚀 Add testing coverage
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-04-15T11:58:52Z" title="Monday, April 15th 2019, 1:58:52 pm +02:00">Apr 15, 2019</time>_
_Closed <time datetime="2019-05-08T22:42:12Z" title="Thursday, May 9th 2019, 12:42:12 am +02:00">May 9, 2019</time>_
---

## :rocket: Feature

We should have an idea of how much of our app is being tested, and enforce some minimum testing coverage

### Is your feature request related to a problem? Please describe.

We are merging in too many components/features with inadequate or no testing

### Describe the prefered solution and alternatives you've considered

Coveralls and Travis CI combo

### PR DESCRIPTION
**Pull request by Tirokk**
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-04-25T20:19:43Z" title="Thursday, April 25th 2019, 10:19:43 pm +02:00">Apr 25, 2019</time>_
_Merged <time datetime="2019-05-06T22:05:33Z" title="Tuesday, May 7th 2019, 12:05:33 am +02:00">May 7, 2019</time>_
---

## Pullrequest

this pull request enables jest to collect test coverage

### Issues

- fixes #469 

### Todo

- [ ] set up travis to with codecov
- [ ] add the badge to our README
- [ ] write lots more tests

### CODE REVIEW

**Comment by Tirokk** [comment]
> [codecov-io](https://github.com/codecov-io) **Authored by [codecov-io](https://github.com/codecov-io)**
_<time datetime="2019-04-25T21:00:32Z" title="Thursday, April 25th 2019, 11:00:32 pm +02:00">Apr 25, 2019</time>_

---


# [Codecov](https://codecov.io/gh/Human-Connection/Human-Connection/pull/504?src=pr&el=h1) Report
> Merging [#504](https://codecov.io/gh/Human-Connection/Human-Connection/pull/504?src=pr&el=desc) into [master](https://codecov.io/gh/Human-Connection/Human-Connection/commit/3cfa5b0cd4e469e979556a20fee69e2d5a981035?src=pr&el=desc) will **increase** coverage by `28.39%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/Human-Connection/Human-Connection/pull/504?src=pr&el=tree)

```diff
@@             Coverage Diff             @@
##           master     #504       +/-   ##
===========================================
+ Coverage   18.63%   47.03%   +28.39%     
===========================================
  Files         113       23       -90     
  Lines        1878      438     -1440     
  Branches       57       57               
===========================================
- Hits          350      206      -144     
+ Misses       1506      210     -1296     
  Partials       22       22
```


| [Impacted Files](https://codecov.io/gh/Human-Connection/Human-Connection/pull/504?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [webapp/plugins/keep-alive.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/504/diff?src=pr&el=tree#diff-d2ViYXBwL3BsdWdpbnMva2VlcC1hbGl2ZS5qcw==) | | |
| [backend/src/middleware/validUrlMiddleware.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/504/diff?src=pr&el=tree#diff-YmFja2VuZC9zcmMvbWlkZGxld2FyZS92YWxpZFVybE1pZGRsZXdhcmUuanM=) | | |
| [backend/src/middleware/activityPubMiddleware.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/504/diff?src=pr&el=tree#diff-YmFja2VuZC9zcmMvbWlkZGxld2FyZS9hY3Rpdml0eVB1Yk1pZGRsZXdhcmUuanM=) | | |
| [backend/src/activitypub/routes/serveUser.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/504/diff?src=pr&el=tree#diff-YmFja2VuZC9zcmMvYWN0aXZpdHlwdWIvcm91dGVzL3NlcnZlVXNlci5qcw==) | | |
| [backend/src/middleware/includedFieldsMiddleware.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/504/diff?src=pr&el=tree#diff-YmFja2VuZC9zcmMvbWlkZGxld2FyZS9pbmNsdWRlZEZpZWxkc01pZGRsZXdhcmUuanM=) | | |
| [backend/src/jest/helpers.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/504/diff?src=pr&el=tree#diff-YmFja2VuZC9zcmMvamVzdC9oZWxwZXJzLmpz) | | |
| [webapp/mixins/seo.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/504/diff?src=pr&el=tree#diff-d2ViYXBwL21peGlucy9zZW8uanM=) | | |
| [backend/src/activitypub/security/index.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/504/diff?src=pr&el=tree#diff-YmFja2VuZC9zcmMvYWN0aXZpdHlwdWIvc2VjdXJpdHkvaW5kZXguanM=) | | |
| [backend/src/seed/factories/reports.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/504/diff?src=pr&el=tree#diff-YmFja2VuZC9zcmMvc2VlZC9mYWN0b3JpZXMvcmVwb3J0cy5qcw==) | | |
| [backend/src/seed/factories/badges.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/504/diff?src=pr&el=tree#diff-YmFja2VuZC9zcmMvc2VlZC9mYWN0b3JpZXMvYmFkZ2VzLmpz) | | |
| ... and [80 more](https://codecov.io/gh/Human-Connection/Human-Connection/pull/504/diff?src=pr&el=tree-more) | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/Human-Connection/Human-Connection/pull/504?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/Human-Connection/Human-Connection/pull/504?src=pr&el=footer). Last update [3cfa5b0...341e4b9](https://codecov.io/gh/Human-Connection/Human-Connection/pull/504?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by Tirokk** [comment]
> [appinteractive](https://github.com/appinteractive) **Authored by [appinteractive](https://github.com/appinteractive)**
_<time datetime="2019-05-02T09:36:27Z" title="Thursday, May 2nd 2019, 11:36:27 am +02:00">May 2, 2019</time>_

---


@roschaefer seems to be hard to get coverage for integration/e2e tests but have a look at that discussion: https://github.com/cypress-io/cypress/issues/346

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-05-03T10:40:44Z" title="Friday, May 3rd 2019, 12:40:44 pm +02:00">May 3, 2019</time>_

---


thanks @appinteractive, I was going to research this later, but you've just saved me time!

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-05-06T21:11:17Z" title="Monday, May 6th 2019, 11:11:17 pm +02:00">May 6, 2019</time>_

---


@mattwr18 can we merge this?

Feel free to merge if it can be.

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-05-06T22:05:29Z" title="Tuesday, May 7th 2019, 12:05:29 am +02:00">May 7, 2019</time>_

---


K, @mattwr18 and I were hangouting, and this is OK to merge

**Review by Mogge — APPROVED** [review]
Looks good to me :+1: 

@mattwr18 can we add codecov for cypress, too?

**Pull request closed without merging**
