### PR TITLE
Added PRIVATE_KEY_PASSPHRASE to needed env vars

### PR DESCRIPTION
**Pull request by Tirokk**
> [Mastercuber](https://github.com/Mastercuber) **Authored by [Mastercuber](https://github.com/Mastercuber)**
_<time datetime="2019-03-25T13:06:06Z" title="Monday, March 25th 2019, 2:06:06 pm +01:00">Mar 25, 2019</time>_
_Merged <time datetime="2019-03-27T22:19:22Z" title="Wednesday, March 27th 2019, 11:19:22 pm +01:00">Mar 27, 2019</time>_
---

### CODE REVIEW

**Comment by Tirokk** [comment]
> [Mastercuber](https://github.com/Mastercuber) **Authored by [Mastercuber](https://github.com/Mastercuber)**
_<time datetime="2019-03-25T13:26:51Z" title="Monday, March 25th 2019, 2:26:51 pm +01:00">Mar 25, 2019</time>_

---


depend on #243

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-03-25T16:07:48Z" title="Monday, March 25th 2019, 5:07:48 pm +01:00">Mar 25, 2019</time>_

---


@Mastercuber I've merged #243 could you:
1. `git fetch upstream/master`
2. `git rebase upstream/master`
3. `git push upstream needed-env-vars --force`

please?

I would like to clean up commits in this PR.

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-03-26T21:21:17Z" title="Tuesday, March 26th 2019, 10:21:17 pm +01:00">Mar 26, 2019</time>_

---


@Mastercuber squash please :green_heart:

**Comment by Tirokk** [comment]
> [Mastercuber](https://github.com/Mastercuber) **Authored by [Mastercuber](https://github.com/Mastercuber)**
_<time datetime="2019-03-26T23:18:27Z" title="Wednesday, March 27th 2019, 12:18:27 am +01:00">Mar 27, 2019</time>_

---


Is done!

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-03-26T23:45:12Z" title="Wednesday, March 27th 2019, 12:45:12 am +01:00">Mar 27, 2019</time>_

---


@Mastercuber Oh, I'm sorry. When I said `squash` I forgot to mention that you better also rebase on the latest `origin/master`. Otherwise we have a lot of conflicts, see above.

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-03-27T00:16:07Z" title="Wednesday, March 27th 2019, 1:16:07 am +01:00">Mar 27, 2019</time>_

---


@Mastercuber *after* you merged `origin/master` or rebased on `origin/master` you can squash the commits. That should clean up the history a little.

**Review by Mogge — APPROVED** [review]

**Pull request closed without merging**
