### PR TITLE
convert email to lowercase before submitting

### LINKED ISSUE #2057: 🐛 [Bug] Password-Reset/Registration Dialogue is Case-Sensitive
> [datenbrei](https://github.com/datenbrei) **Authored by [datenbrei](https://github.com/datenbrei)**
_<time datetime="2019-10-28T12:22:02Z" title="Monday, October 28th 2019, 1:22:02 pm +01:00">Oct 28, 2019</time>_
_Closed <time datetime="2019-11-07T08:52:48Z" title="Thursday, November 7th 2019, 9:52:48 am +01:00">Nov 7, 2019</time>_
---

## :bug: Bugreport
When users want to reset their passwords or want to register and they use emails with uppcercase in it, these can not be found and you get an email which says:  _You requested a password reset but unfortunately we couldn't find an account associated with your e-mail address. Did you maybe use another one when you signed up?_

wrong-email

### Steps to reproduce the behavior
1. Open reset Password dialogue
2. Type in your emial with upper case letters

Screenshot - 2019-10-29T171429 064

Screenshot - 2019-10-29T171929 698

### Expected behavior
The given email for reset should be converted to lowercase

### Version & Environment
any

### PR DESCRIPTION
**Pull request by Tirokk**
> [StephenHogsten](https://github.com/StephenHogsten) **Authored by [StephenHogsten](https://github.com/StephenHogsten)**
_<time datetime="2019-10-30T17:56:15Z" title="Wednesday, October 30th 2019, 6:56:15 pm +01:00">Oct 30, 2019</time>_
_Closed <time datetime="2019-11-04T23:57:31Z" title="Tuesday, November 5th 2019, 12:57:31 am +01:00">Nov 5, 2019</time>_
---

Convert user inputted email to lowercase when requesting a password reset

### Issues
- fixes #2057

### CODE REVIEW

**Comment by Tirokk** [comment]
> [StephenHogsten](https://github.com/StephenHogsten) **Authored by [StephenHogsten](https://github.com/StephenHogsten)**
_<time datetime="2019-10-30T17:57:39Z" title="Wednesday, October 30th 2019, 6:57:39 pm +01:00">Oct 30, 2019</time>_

---


Just saw the last comment in the issue.  I will take a look at the backend

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-10-31T18:06:40Z" title="Thursday, October 31st 2019, 7:06:40 pm +01:00">Oct 31, 2019</time>_

---


@StephenHogsten apparently @Kachulio1 is already working on the backend. Look here:
https://github.com/Human-Connection/Human-Connection/pull/2100

It would be great if you two could join forces :slightly_smiling_face: if you need help to write some tests for the password reset, feel free to ask me for a pair-programming!

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-11-04T20:17:02Z" title="Monday, November 4th 2019, 9:17:02 pm +01:00">Nov 4, 2019</time>_

---


@StephenHogsten and @Kachulio1 I'm going to incorporate your both commits into a dedicated branch and create a PR from that, OK? I'll also add tests.

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-11-04T23:57:31Z" title="Tuesday, November 5th 2019, 12:57:31 am +01:00">Nov 5, 2019</time>_

---


@StephenHogsten I'll close this in favour of https://github.com/Human-Connection/Human-Connection/pull/2118 your commit is still there and you'll join the repository's conributors list when it's merged.

**Comment by Tirokk** [comment]
> [StephenHogsten](https://github.com/StephenHogsten) **Authored by [StephenHogsten](https://github.com/StephenHogsten)**
_<time datetime="2019-11-05T18:57:02Z" title="Tuesday, November 5th 2019, 7:57:02 pm +01:00">Nov 5, 2019</time>_

---


@roschaefer just going back through all the comments.  Do you want me to work on anything on the new PR?  Or are other people already taking care of everything?

**Review by Mogge — CHANGES_REQUESTED** [review]
hey @StephenHogsten, this is great a couple things
1) can you please clone the repo directly, and we can give you permissions to push to it? We have encrypted variables in Travis, so no `PR`s from forks will pass the build see https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml
2) it is also failing because of linting issues, can you run `yarn lint --fix` from the `/webapp` and `/backend` directories?

**Pull request closed without merging**
