### PR TITLE
402 userprofile shouted tab 2

### PR DESCRIPTION
**Pull request by Tirokk**
> [ogerly](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-06-05T08:56:55Z" title="Wednesday, June 5th 2019, 10:56:55 am +02:00">Jun 5, 2019</time>_
_Merged <time datetime="2019-06-05T10:57:22Z" title="Wednesday, June 5th 2019, 12:57:22 pm +02:00">Jun 5, 2019</time>_
---

## 🍰 Pullrequest
402-userprofile-shouted-tab - text adapted for single or multiple. / css extended.
 
gif

the basis for this PR is the PR: https://github.com/Human-Connection/Human-Connection/pull/672
### Issues
- relates 402

### Todo

- [X] None

### CODE REVIEW

**Comment by Tirokk** [comment]
> [ogerly](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-06-05T09:04:06Z" title="Wednesday, June 5th 2019, 11:04:06 am +02:00">Jun 5, 2019</time>_

---


in the field commented ?
1. comments written by a user in contributions to other users?
or
2. comments he has received on his own contributions?
or
3. Both?
@ulfgebhardt @roschaefer @Tirokk @mattwr18

**Comment by Tirokk** [comment]
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2019-06-05T10:23:50Z" title="Wednesday, June 5th 2019, 12:23:50 pm +02:00">Jun 5, 2019</time>_

---


Accidentally closed …

**Comment by Tirokk** [comment]
> [codecov[bot]](https://github.com/apps/codecov) **Authored by [codecov[bot]](https://github.com/apps/codecov)**
_<time datetime="2019-06-05T10:42:16Z" title="Wednesday, June 5th 2019, 12:42:16 pm +02:00">Jun 5, 2019</time>_

---


# [Codecov](https://codecov.io/gh/Human-Connection/Human-Connection/pull/752?src=pr&el=h1) Report
> Merging [#752](https://codecov.io/gh/Human-Connection/Human-Connection/pull/752?src=pr&el=desc) into [master](https://codecov.io/gh/Human-Connection/Human-Connection/commit/dc84b913d4f7743fc9628dcbd2acb2b16726c64d?src=pr&el=desc) will **not change** coverage.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/Human-Connection/Human-Connection/pull/752?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##           master     #752   +/-   ##
=======================================
  Coverage   23.76%   23.76%           
=======================================
  Files         165      165           
  Lines        2323     2323           
  Branches      120      120           
=======================================
  Hits          552      552           
  Misses       1736     1736           
  Partials       35       35
```


| [Impacted Files](https://codecov.io/gh/Human-Connection/Human-Connection/pull/752?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [webapp/pages/profile/\_id/\_slug.vue](https://codecov.io/gh/Human-Connection/Human-Connection/pull/752/diff?src=pr&el=tree#diff-d2ViYXBwL3BhZ2VzL3Byb2ZpbGUvX2lkL19zbHVnLnZ1ZQ==) | `29.55% <ø> (ø)` | :arrow_up: |

**Comment by Tirokk** [comment]
> [ogerly](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-06-05T10:57:50Z" title="Wednesday, June 5th 2019, 12:57:50 pm +02:00">Jun 5, 2019</time>_

---


giphcccy

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-06-05T11:41:37Z" title="Wednesday, June 5th 2019, 1:41:37 pm +02:00">Jun 5, 2019</time>_

---


you're so quick @Tirokk... I didn't get a chance to have a proper look, but it looks great @ogerly 
Thanks!!!

Also, I really appreciate people starting to upload screenshots/gif so that others can quickly see the changes!!! @roschaefer @ulfgebhardt

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-06-05T11:41:37Z" title="Wednesday, June 5th 2019, 1:41:37 pm +02:00">Jun 5, 2019</time>_

---


you're so quick @Tirokk... I didn't get a chance to have a proper look, but it looks great @ogerly 
Thanks!!!

Also, I really appreciate people starting to upload screenshots/gif so that others can quickly see the changes!!! @roschaefer @ulfgebhardt

**Review by Mogge — APPROVED** [review]
Great work @ogerly !!! 💫🚀

**Pull request closed without merging**
