### PR TITLE
User can not anymore delete Comments of others

### LINKED ISSUE #728: 🐛 User can delete Comments of others …
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2019-06-03T16:59:05Z" title="Monday, June 3rd 2019, 6:59:05 pm +02:00">Jun 3, 2019</time>_
_Closed <time datetime="2019-06-03T21:02:09Z" title="Monday, June 3rd 2019, 11:02:09 pm +02:00">Jun 3, 2019</time>_
---

## :bug: Bugreport

User should only be able to delete it’s own Comments!

### PR DESCRIPTION
**Pull request by Tirokk**
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2019-06-03T17:09:52Z" title="Monday, June 3rd 2019, 7:09:52 pm +02:00">Jun 3, 2019</time>_
_Merged <time datetime="2019-06-03T21:02:09Z" title="Monday, June 3rd 2019, 11:02:09 pm +02:00">Jun 3, 2019</time>_
---

## 🍰 Pullrequest

Changed Permissions Middleware to assure that a user can only delete it’s own comments.
Written a Jest test to test this.

### Issues

- fixes #728

### CODE REVIEW

**Comment by Tirokk** [comment]
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2019-06-03T19:32:01Z" title="Monday, June 3rd 2019, 9:32:01 pm +02:00">Jun 3, 2019</time>_

---


Codecov value for Backend is bullshit!
I created no new code and wrote a backend test, so how can it sink?

**Comment by Tirokk** [comment]
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2019-06-03T19:35:13Z" title="Monday, June 3rd 2019, 9:35:13 pm +02:00">Jun 3, 2019</time>_

---


Thank you @mattwr18 !!!
As well for your aprovement.

At the moment an admin should only disable a comment and not delete it, as far I do understand.

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-06-03T19:41:43Z" title="Monday, June 3rd 2019, 9:41:43 pm +02:00">Jun 3, 2019</time>_

---


I think this is because there were changes merged in since you last pulled in the changes to master @Tirokk,I'll merge in the latest changes and push it back up to see if I'm correct

**Comment by Tirokk** [comment]
> [codecov[bot]](https://github.com/apps/codecov) **Authored by [codecov[bot]](https://github.com/apps/codecov)**
_<time datetime="2019-06-03T20:14:15Z" title="Monday, June 3rd 2019, 10:14:15 pm +02:00">Jun 3, 2019</time>_

---


# [Codecov](https://codecov.io/gh/Human-Connection/Human-Connection/pull/729?src=pr&el=h1) Report
> Merging [#729](https://codecov.io/gh/Human-Connection/Human-Connection/pull/729?src=pr&el=desc) into [master](https://codecov.io/gh/Human-Connection/Human-Connection/commit/7272c5002d0686a387195e79f090f20a97228948?src=pr&el=desc) will **not change** coverage.
> The diff coverage is `0%`.

[Impacted file tree graph](https://codecov.io/gh/Human-Connection/Human-Connection/pull/729?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##           master     #729   +/-   ##
=======================================
  Coverage   22.95%   22.95%           
=======================================
  Files         163      163           
  Lines        2309     2309           
  Branches      119      119           
=======================================
  Hits          530      530           
  Misses       1744     1744           
  Partials       35       35
```


| [Impacted Files](https://codecov.io/gh/Human-Connection/Human-Connection/pull/729?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [backend/src/middleware/permissionsMiddleware.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/729/diff?src=pr&el=tree#diff-YmFja2VuZC9zcmMvbWlkZGxld2FyZS9wZXJtaXNzaW9uc01pZGRsZXdhcmUuanM=) | `0% <0%> (ø)` | :arrow_up: |

**Review by Mogge — APPROVED** [review]
Great job @Tirokk!!!
that makes me feel better! I guess an admin cannot delete a comment either? 
what they would do is disable it?

**Review by Mogge — APPROVED** [review]

**Pull request closed without merging**
