### PR TITLE
Maintenance service to support maintenance mode

### LINKED ISSUE #906: 🚀 [Feature] Maintenance Mode
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-06-25T12:07:55Z" title="Tuesday, June 25th 2019, 2:07:55 pm +02:00">Jun 25, 2019</time>_
_Closed <time datetime="2019-07-29T08:50:53Z" title="Monday, July 29th 2019, 10:50:53 am +02:00">Jul 29, 2019</time>_
---

## :rocket: Feature

We need to have a page that user's see when we are doing maintenance on the site

### PR DESCRIPTION
**Pull request by Tirokk**
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-07-02T22:47:17Z" title="Wednesday, July 3rd 2019, 12:47:17 am +02:00">Jul 3, 2019</time>_
_Merged <time datetime="2019-07-29T08:50:53Z" title="Monday, July 29th 2019, 10:50:53 am +02:00">Jul 29, 2019</time>_
---

### Issues

- fixes #906 

@roschaefer, so far this is what I have done... I'm sure I've made some mistakes, but at least this is a start and maybe we can get it figured out together?

following the docs here: https://www.linode.com/docs/applications/containers/how-to-deploy-nginx-on-a-kubernetes-cluster/#deploy-nginx-on-the-kubernetes-cluster

I created a deployment with `kubectl --namespace=human-connection create deployment nginx --image=nginx`

Screenshot at 2019-07-02 19:40:39

Then, I created a service `kubectl --namespace=human-connection create service nodeport nginx --tcp=80:80`

Screenshot at 2019-07-02 19:41:51

it's info:
Screenshot at 2019-07-02 19:42:36

I then copied the `service-web.yaml` and changed the selector like it says here: https://www.nrmitchi.com/2017/11/easy-maintenance-mode-in-kubernetes/, but I noticed that the label doesn't match for example and also maybe the service should be named `maintenance`, as above.

Also, I had a doubt about this line `This isolated service contains only an nginx container, with our generic Maintenance page preloaded.`... 
If I am not mistaken the nginx container exists now, but how can I preload a maintenance page? With `apply` and some config? sshing into the nginx container and creating it?

Just a start...

### CODE REVIEW

**Comment by Tirokk** [comment]
> [codecov[bot]](https://github.com/apps/codecov) **Authored by [codecov[bot]](https://github.com/apps/codecov)**
_<time datetime="2019-07-03T17:27:56Z" title="Wednesday, July 3rd 2019, 7:27:56 pm +02:00">Jul 3, 2019</time>_

---


# [Codecov](https://codecov.io/gh/Human-Connection/Human-Connection/pull/956?src=pr&el=h1) Report
> :exclamation: No coverage uploaded for pull request base (`master@324330a`). [Click here to learn what that means](https://docs.codecov.io/docs/error-reference#section-missing-base-commit).
> The diff coverage is `n/a`.

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-07-10T08:56:24Z" title="Wednesday, July 10th 2019, 10:56:24 am +02:00">Jul 10, 2019</time>_

---


@mattwr18 oh, I forgot one thing: The nginx should respond with 503!

@mattwr18 do you want to take care of that? And maybe make the page look a bit more fancy? :smile:

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-07-10T09:59:47Z" title="Wednesday, July 10th 2019, 11:59:47 am +02:00">Jul 10, 2019</time>_

---


yes, I do @roschaefer 
I'll have a look at the documentation as well, as I understood it instead of editing to add the `command: ["tail", etc...]`, we edit to swap out the name of the service, then change it back

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-07-29T07:16:52Z" title="Monday, July 29th 2019, 9:16:52 am +02:00">Jul 29, 2019</time>_

---


@roschaefer, I made the page mobile responsive and used the font family and line height from our styleguide... here is what it looks like:
Ipad:
Screenshot at 2019-07-29 09:13:02
Screenshot at 2019-07-29 09:12:47
Iphone:
Screenshot at 2019-07-29 09:12:37
Screenshot at 2019-07-29 09:12:17
Desktop:
Screenshot at 2019-07-29 09:12:07

Probably not award-winning stuff, but I think good enough for the maintenance page, until/if the marketing gets back to us with a different pic, or we'd like to change the message in some way. What do you think?

**Review by Mogge — APPROVED** [review]
Works! All I had to do is to push the docker image to dockerhub. @mattwr18 I added documentation how to use maintenance mode.

easy

All that's left is basic styling of our current blank HTML page and the nice styled up version here: 
https://github.com/Human-Connection/WebApp/blob/develop/layouts/error.vue

**Review by Mogge — APPROVED** [review]
Wow @mattwr18 !!!
We get a step further again. 🚀💫
You get sophisticated stuff done. That's admirable. ❤️

Big thanks @roschaefer for adding documentation. 😍

Heart showing girl

**Pull request closed without merging**
