### PR TITLE
fix(webapp): remove ribbon z-index

### LINKED ISSUE #3141: [Bug] "Post" Ribbons visible over main-navigation and PageFooter
> [rbeer](https://github.com/rbeer) **Authored by [rbeer](https://github.com/rbeer)**
_<time datetime="2020-02-23T07:35:45Z" title="Sunday, February 23rd 2020, 8:35:45 am +01:00">Feb 23, 2020</time>_
_Closed <time datetime="2020-02-24T22:21:50Z" title="Monday, February 24th 2020, 11:21:50 pm +01:00">Feb 24, 2020</time>_
---

## :bug: Bugreport
Blue "Post" `Ribbon`s on posts are visible above the main navigation, when scrolling down.
hc_post_ribbons

### Steps to reproduce the behavior
1. Log in @ https://develop.human-connection.org/
2. Scroll down

### Expected behavior
Ribbons should follow their posts, disappearing below the navigation.

### Version & Environment
 Type: Desktop, Chrome - should affect all, though
 - OS: `GNU/Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 x86_64` 
 - Browser: `Brave | 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)`

### Additional context

[/webapp/components/Ribbon/index.vue](https://github.com/Human-Connection/Human-Connection/blob/fa32c5789b5fcbc0881f56f601a2015eada18f8a/webapp/components/Ribbon/index.vue#L35) sets a `z-index` of `11`, where [/webapp/assets/styles/main.scss](https://github.com/Human-Connection/Human-Connection/blob/fa32c5789b5fcbc0881f56f601a2015eada18f8a/webapp/assets/styles/main.scss#L98) defines a `z-index` of `10` for `.main-navigation`.

### Possible solution
I can't see a case where something would ever want to be rendered above it, so setting `.main-navigation`'s `z-index` to a rather high value like `100` would fix this issue and prevent future bugs of this nature.

### PR DESCRIPTION
**Pull request by Tirokk**
> [alina-beck](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2020-02-24T21:24:42Z" title="Monday, February 24th 2020, 10:24:42 pm +01:00">Feb 24, 2020</time>_
_Merged <time datetime="2020-02-24T22:21:49Z" title="Monday, February 24th 2020, 11:21:49 pm +01:00">Feb 24, 2020</time>_
---

## 🍰 Pullrequest
refactor and fix ribbon CSS

### Issues
- fixes #3141

### CODE REVIEW

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-02-24T22:03:41Z" title="Monday, February 24th 2020, 11:03:41 pm +01:00">Feb 24, 2020</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/5555/specs"></a> <b title="Passed">66</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/5555/failures"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | 39dc277d0e <span style="cursor:help;" title="Your CI provider generated this commit by merging this branch into the target branch.">ℹ️</span> |
| **Started** | Feb 24, 2020 9:42 PM |
| **Ended** | Feb 24, 2020 10:03 PM |
| **Duration** | 21:17 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Firefox 68  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/5555/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings)

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-02-24T22:05:29Z" title="Monday, February 24th 2020, 11:05:29 pm +01:00">Feb 24, 2020</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/5554/specs"></a> <b title="Passed">66</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/5554/failures"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | 21eae3dcd2 |
| **Started** | Feb 24, 2020 9:41 PM |
| **Ended** | Feb 24, 2020 10:05 PM |
| **Duration** | 23:52 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Firefox 68  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/5554/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings)

**Review by Mogge — APPROVED** [review]
it works! and it's great you've deleting more lines of code than you've added!!

**Review by Mogge — APPROVED** [review]
Works for me™
works for me

**Pull request closed without merging**
