### PR TITLE
Send only one notification for mention and comment

### LINKED ISSUE #1953: 🐛 [Bug] Two Notifications for just one Comment
> [datenbrei](https://github.com/datenbrei) **Authored by [datenbrei](https://github.com/datenbrei)**
_<time datetime="2019-10-18T13:40:05Z" title="Friday, October 18th 2019, 3:40:05 pm +02:00">Oct 18, 2019</time>_
_Closed <time datetime="2019-10-31T16:45:29Z" title="Thursday, October 31st 2019, 5:45:29 pm +01:00">Oct 31, 2019</time>_
---

## :bug: Bugreport
If somebody comments on my post and also mentions my with @myself then I get two notifications for just one comment.

double

### Steps to reproduce the behavior
1. A user writes a comment and mentions me
2. I get two notifications (see above)

### Expected behavior
For every comment arriving there should be just one notification.

### PR DESCRIPTION
**Pull request by Tirokk**
> [KapilJ22](https://github.com/KapilJ22) **Authored by [KapilJ22](https://github.com/KapilJ22)**
_<time datetime="2019-10-28T19:41:34Z" title="Monday, October 28th 2019, 8:41:34 pm +01:00">Oct 28, 2019</time>_
_Merged <time datetime="2019-10-31T16:45:29Z" title="Thursday, October 31st 2019, 5:45:29 pm +01:00">Oct 31, 2019</time>_
---

### Issues

- fixes #1953

### Todo

- [X] None

### CODE REVIEW

**Comment by Tirokk** [comment]
> [KapilJ22](https://github.com/KapilJ22) **Authored by [KapilJ22](https://github.com/KapilJ22)**
_<time datetime="2019-10-31T10:47:42Z" title="Thursday, October 31st 2019, 11:47:42 am +01:00">Oct 31, 2019</time>_

---


> I just wanted to let you know I have had a look, and tested it out @KapilJ22
> I would like to discuss this in our daily standup before approving since we need to make a decision on which reason to prioritize with the notification...

Sounds good @mattwr18 !

**Comment by Tirokk** [comment]
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2019-10-31T12:45:02Z" title="Thursday, October 31st 2019, 1:45:02 pm +01:00">Oct 31, 2019</time>_

---


I would prioritise from my first intuition to the most personal reason.
This is the mention in my eyes … @KapilJ22 @mattwr18 
Or add a new reason for the combination of both …

**Comment by Tirokk** [comment]
> [KapilJ22](https://github.com/KapilJ22) **Authored by [KapilJ22](https://github.com/KapilJ22)**
_<time datetime="2019-10-31T15:45:46Z" title="Thursday, October 31st 2019, 4:45:46 pm +01:00">Oct 31, 2019</time>_

---


> good enough
> 
> Great! @KapilJ22 from my commit message:
> 
> ```
> refactor: small refactoring for readability
> 
> @KapilJ your solution is right now the best solution, I think. Probably
> the ideal solution would be if we could implement the `CreateComment`
> resolver in such a way that it is doing eager loading of the
> `comment->post->author` relationship and resolving a commment object
> which has the required objects all set. Then you wouldn't have to
> refetch all the stuff.
> 
> But I think this is OK for now :+1:
> ```

Thanks for your review and refactoring @roschaefer - you are awesome :).

**Review by Mogge — APPROVED** [review]
good enough

Great! @KapilJ22 from my commit message:

    refactor: small refactoring for readability

    @KapilJ your solution is right now the best solution, I think. Probably
    the ideal solution would be if we could implement the `CreateComment`
    resolver in such a way that it is doing eager loading of the
    `comment->post->author` relationship and resolving a commment object
    which has the required objects all set. Then you wouldn't have to
    refetch all the stuff.

    But I think this is OK for now :+1:

**Pull request closed without merging**
