### PR TITLE
a contribution that has been blocked can be released again

### PR DESCRIPTION
**Pull request by Tirokk**
> [ogerly](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-05-16T18:00:08Z" title="Thursday, May 16th 2019, 8:00:08 pm +02:00">May 16, 2019</time>_
_Merged <time datetime="2019-05-20T16:16:52Z" title="Monday, May 20th 2019, 6:16:52 pm +02:00">May 20, 2019</time>_
---

## Pullrequest

1. a contribution that has been blocked can be released again. it will also be reloaded after blocking and after releasing after 1500 ms.
2. superfluous file deleted, code cleaned from alerts and console.log

### Issues

- [X] #525 

### Checklist

- [X] None

### How2Test

- [X] None

### Todo

- [X] None

### CODE REVIEW

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-05-17T03:20:42Z" title="Friday, May 17th 2019, 5:20:42 am +02:00">May 17, 2019</time>_

---


@ogerly I think you might have put in this PR with the feature branch as the base, since it says you want to merge `379` commits into your feature branch from master...

you want to use `master` as the base branch and request that your changes in the feature branch get merged into it.

**Comment by Tirokk** [comment]
> [codecov[bot]](https://github.com/apps/codecov) **Authored by [codecov[bot]](https://github.com/apps/codecov)**
_<time datetime="2019-05-20T12:49:52Z" title="Monday, May 20th 2019, 2:49:52 pm +02:00">May 20, 2019</time>_

---


# [Codecov](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615?src=pr&el=h1) Report
> :exclamation: No coverage uploaded for pull request base (`2019/kw17/release_post2@389f22a`). [Click here to learn what that means](https://docs.codecov.io/docs/error-reference#section-missing-base-commit).
> The diff coverage is `56.41%`.

[Impacted file tree graph](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615?src=pr&el=tree)

```diff
@@                    Coverage Diff                     @@
##             2019/kw17/release_post2     #615   +/-   ##
==========================================================
  Coverage                           ?   20.11%           
==========================================================
  Files                              ?      157           
  Lines                              ?     2208           
  Branches                           ?      105           
==========================================================
  Hits                               ?      444           
  Misses                             ?     1740           
  Partials                           ?       24
```


| [Impacted Files](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [webapp/components/Empty.vue](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615/diff?src=pr&el=tree#diff-d2ViYXBwL2NvbXBvbmVudHMvRW1wdHkudnVl) | `100% <ø> (ø)` | |
| [backend/src/seed/factories/comments.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615/diff?src=pr&el=tree#diff-YmFja2VuZC9zcmMvc2VlZC9mYWN0b3JpZXMvY29tbWVudHMuanM=) | `100% <ø> (ø)` | |
| [backend/src/middleware/userMiddleware.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615/diff?src=pr&el=tree#diff-YmFja2VuZC9zcmMvbWlkZGxld2FyZS91c2VyTWlkZGxld2FyZS5qcw==) | `0% <ø> (ø)` | |
| [webapp/pages/login.vue](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615/diff?src=pr&el=tree#diff-d2ViYXBwL3BhZ2VzL2xvZ2luLnZ1ZQ==) | `0% <ø> (ø)` | |
| [backend/src/seed/seed-db.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615/diff?src=pr&el=tree#diff-YmFja2VuZC9zcmMvc2VlZC9zZWVkLWRiLmpz) | `0% <ø> (ø)` | |
| [backend/src/graphql-schema.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615/diff?src=pr&el=tree#diff-YmFja2VuZC9zcmMvZ3JhcGhxbC1zY2hlbWEuanM=) | `0% <ø> (ø)` | |
| [backend/src/middleware/permissionsMiddleware.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615/diff?src=pr&el=tree#diff-YmFja2VuZC9zcmMvbWlkZGxld2FyZS9wZXJtaXNzaW9uc01pZGRsZXdhcmUuanM=) | `0% <ø> (ø)` | |
| [backend/src/middleware/index.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615/diff?src=pr&el=tree#diff-YmFja2VuZC9zcmMvbWlkZGxld2FyZS9pbmRleC5qcw==) | `0% <ø> (ø)` | |
| [backend/src/seed/factories/users.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615/diff?src=pr&el=tree#diff-YmFja2VuZC9zcmMvc2VlZC9mYWN0b3JpZXMvdXNlcnMuanM=) | `100% <ø> (ø)` | |
| [webapp/graphql/CommentQuery.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615/diff?src=pr&el=tree#diff-d2ViYXBwL2dyYXBocWwvQ29tbWVudFF1ZXJ5Lmpz) | `0% <0%> (ø)` | |
| ... and [22 more](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615/diff?src=pr&el=tree-more) | |

**Comment by Tirokk** [comment]
> [codecov[bot]](https://github.com/apps/codecov) **Authored by [codecov[bot]](https://github.com/apps/codecov)**
_<time datetime="2019-05-20T12:49:52Z" title="Monday, May 20th 2019, 2:49:52 pm +02:00">May 20, 2019</time>_

---


# [Codecov](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615?src=pr&el=h1) Report
> :exclamation: No coverage uploaded for pull request base (`2019/kw17/release_post2@389f22a`). [Click here to learn what that means](https://docs.codecov.io/docs/error-reference#section-missing-base-commit).
> The diff coverage is `56.41%`.

[Impacted file tree graph](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615?src=pr&el=tree)

```diff
@@                    Coverage Diff                     @@
##             2019/kw17/release_post2     #615   +/-   ##
==========================================================
  Coverage                           ?   20.11%           
==========================================================
  Files                              ?      157           
  Lines                              ?     2208           
  Branches                           ?      105           
==========================================================
  Hits                               ?      444           
  Misses                             ?     1740           
  Partials                           ?       24
```


| [Impacted Files](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [webapp/components/Empty.vue](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615/diff?src=pr&el=tree#diff-d2ViYXBwL2NvbXBvbmVudHMvRW1wdHkudnVl) | `100% <ø> (ø)` | |
| [backend/src/seed/factories/comments.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615/diff?src=pr&el=tree#diff-YmFja2VuZC9zcmMvc2VlZC9mYWN0b3JpZXMvY29tbWVudHMuanM=) | `100% <ø> (ø)` | |
| [backend/src/middleware/userMiddleware.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615/diff?src=pr&el=tree#diff-YmFja2VuZC9zcmMvbWlkZGxld2FyZS91c2VyTWlkZGxld2FyZS5qcw==) | `0% <ø> (ø)` | |
| [webapp/pages/login.vue](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615/diff?src=pr&el=tree#diff-d2ViYXBwL3BhZ2VzL2xvZ2luLnZ1ZQ==) | `0% <ø> (ø)` | |
| [backend/src/seed/seed-db.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615/diff?src=pr&el=tree#diff-YmFja2VuZC9zcmMvc2VlZC9zZWVkLWRiLmpz) | `0% <ø> (ø)` | |
| [backend/src/graphql-schema.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615/diff?src=pr&el=tree#diff-YmFja2VuZC9zcmMvZ3JhcGhxbC1zY2hlbWEuanM=) | `0% <ø> (ø)` | |
| [backend/src/middleware/permissionsMiddleware.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615/diff?src=pr&el=tree#diff-YmFja2VuZC9zcmMvbWlkZGxld2FyZS9wZXJtaXNzaW9uc01pZGRsZXdhcmUuanM=) | `0% <ø> (ø)` | |
| [backend/src/middleware/index.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615/diff?src=pr&el=tree#diff-YmFja2VuZC9zcmMvbWlkZGxld2FyZS9pbmRleC5qcw==) | `0% <ø> (ø)` | |
| [backend/src/seed/factories/users.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615/diff?src=pr&el=tree#diff-YmFja2VuZC9zcmMvc2VlZC9mYWN0b3JpZXMvdXNlcnMuanM=) | `100% <ø> (ø)` | |
| [webapp/graphql/CommentQuery.js](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615/diff?src=pr&el=tree#diff-d2ViYXBwL2dyYXBocWwvQ29tbWVudFF1ZXJ5Lmpz) | `0% <0%> (ø)` | |
| ... and [22 more](https://codecov.io/gh/Human-Connection/Human-Connection/pull/615/diff?src=pr&el=tree-more) | |

**Review by Mogge — CHANGES_REQUESTED** [review]
Screenshot - 2019-05-16T233516 170

# What happened?
what happened?

**Pull request closed without merging**
