### PR TITLE
added Russian to locales

### PR DESCRIPTION
**Pull request by Tirokk**
> [ewanold](https://github.com/ewanold) **Authored by [ewanold](https://github.com/ewanold)**
_<time datetime="2019-11-02T15:35:57Z" title="Saturday, November 2nd 2019, 4:35:57 pm +01:00">Nov 2, 2019</time>_
_Merged <time datetime="2019-11-11T13:38:00Z" title="Monday, November 11th 2019, 2:38:00 pm +01:00">Nov 11, 2019</time>_
---

## 🍰 Pullrequest
added Russian to locales

### Issues
- None

### Todo
wait for ru.json to automagically show up?

### CODE REVIEW

**Comment by Tirokk** [comment]
> [ogerly](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-11-03T06:00:18Z" title="Sunday, November 3rd 2019, 7:00:18 am +01:00">Nov 3, 2019</time>_

---


Are you also doing the Russian translation?

**Comment by Tirokk** [comment]
> [ewanold](https://github.com/ewanold) **Authored by [ewanold](https://github.com/ewanold)**
_<time datetime="2019-11-03T07:04:09Z" title="Sunday, November 3rd 2019, 8:04:09 am +01:00">Nov 3, 2019</time>_

---




> Are you also doing the Russian translation?

I finished the informal part just yesterday and plan on continuing so.  
It is a great learning opportunity:-)

-- 
Ewald Arnold
mailto:ewald at ewald-arnold dot de
mailto:mobil at ewald-arnold dot de

**Comment by Tirokk** [comment]
> [vbelolapotkov](https://github.com/vbelolapotkov) **Authored by [vbelolapotkov](https://github.com/vbelolapotkov)**
_<time datetime="2019-11-03T07:22:18Z" title="Sunday, November 3rd 2019, 8:22:18 am +01:00">Nov 3, 2019</time>_

---


@ewanold FYI, I can help with RU translations if needed.

**Comment by Tirokk** [comment]
> [ewanold](https://github.com/ewanold) **Authored by [ewanold](https://github.com/ewanold)**
_<time datetime="2019-11-03T07:55:18Z" title="Sunday, November 3rd 2019, 8:55:18 am +01:00">Nov 3, 2019</time>_

---


> @ewanold FYI, I can help with RU translations if needed.

That would be unexpectedly awesome :-) A native person with actual understanding of the workings around the translations is ideal. So far Mr. Yan Dex was my best friend, as well as other translations on lokalise I could guess from. 

Would you mind sharing private email or Telegram (which I have on the desktop as well)?

**Comment by Tirokk** [comment]
> [vbelolapotkov](https://github.com/vbelolapotkov) **Authored by [vbelolapotkov](https://github.com/vbelolapotkov)**
_<time datetime="2019-11-03T09:58:07Z" title="Sunday, November 3rd 2019, 10:58:07 am +01:00">Nov 3, 2019</time>_

---


Yeah, sure. 
My email is belolapotkov.v@gmail.com
Tg: vbelolapotkov

**Comment by Tirokk** [comment]
> [ogerly](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-11-03T14:19:10Z" title="Sunday, November 3rd 2019, 3:19:10 pm +01:00">Nov 3, 2019</time>_

---


nice that you do this together. please add the ru.json to this PR. then it's great :)

**Comment by Tirokk** [comment]
> [ewanold](https://github.com/ewanold) **Authored by [ewanold](https://github.com/ewanold)**
_<time datetime="2019-11-03T16:53:20Z" title="Sunday, November 3rd 2019, 5:53:20 pm +01:00">Nov 3, 2019</time>_

---


> nice that you do this together. please add the ru.json to this PR. then it's great :)

not sure if it's what you meant, but I added an *empty* ru.json. That's all I have so far. I assumed there is some background process pulling the files from lokalise, at least there is a lokalise bot in the member list. Am I mistaken? I tried downloading the file via lokalise API, but it would not let me, probably due to permissions.

If there is something prepared but not working yet, because people have more important things to do right now, I might try and look into it. Just point me in the right direction. I am a firm believer in automation :-)

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-11-04T17:26:44Z" title="Monday, November 4th 2019, 6:26:44 pm +01:00">Nov 4, 2019</time>_

---


@ewanold @vbelolapotkov if you are interested in some automation:

```bash
jq -s '.[0] * .[1]' <(jq 'walk(if type == "string" then null else . end)' en.json) ru.json
```

This command in a POSIX shell (e.g. bash) should produce an output for Russian with all missing keys and a value `null`.

**Comment by Tirokk** [comment]
> [ewanold](https://github.com/ewanold) **Authored by [ewanold](https://github.com/ewanold)**
_<time datetime="2019-11-04T18:40:06Z" title="Monday, November 4th 2019, 7:40:06 pm +01:00">Nov 4, 2019</time>_

---


 @vbelolapotkov  @roschaefer

> jq -s '.[0] * .[1]' <(jq 'walk(if type == "string" then null else . end)' en.json) ru.json

thanks, but you (or maybe someone else?) sent me this trick already :-) but I still feel I am missing the bigger picture. How exactly is lokalise connected to github? Is there some automation meant to run? https://github.com/lokalise-bot has not done much so far :-) Am I supposed to "manually" add the missing keys to ru.json and then into git, from where they are transferred to lokalise and back somehow? 

If there is no full round-trip for data transfer yet, I would like to try and set it up. It may be no big problem now, but once HC gains momentum (and it will :-) we should be able to deliver languages and updates quickly. Most people prefer their native language and a mix gives at least bad first impressions.

And one last question: how do the formal variants come into play?

BTW: nice dancing performance, I wasn't aware of skirts for men :-)

**Comment by Tirokk** [comment]
> [ewanold](https://github.com/ewanold) **Authored by [ewanold](https://github.com/ewanold)**
_<time datetime="2019-11-04T19:05:53Z" title="Monday, November 4th 2019, 8:05:53 pm +01:00">Nov 4, 2019</time>_

---


> @vbelolapotkov @ewanold can you have a double check if adding your location etc. work?

not fully sure if it's what you meant, but the 5 commits including your changes to add the Russian names look reasonable to me. Hamburg became Gamburg as it should be :-)

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-11-04T19:42:12Z" title="Monday, November 4th 2019, 8:42:12 pm +01:00">Nov 4, 2019</time>_

---


@ewanold I don't know localise myself.

If you signup at lokalise you can join this project: https://lokalise.com/project/556252725c18dd752dd546.13222042/ I can give you admin powers if you want. You can pull the localizations and translate them there. Apparently you can also create a new PR from lokalise. I triggered at least the direction from Github to lokalise manually, a couple of days ago.

**Comment by Tirokk** [comment]
> [ewanold](https://github.com/ewanold) **Authored by [ewanold](https://github.com/ewanold)**
_<time datetime="2019-11-04T20:45:36Z" title="Monday, November 4th 2019, 9:45:36 pm +01:00">Nov 4, 2019</time>_

---


> If you signup at lokalise you can join this project: https://lokalise.com/project

I already signed up to translate the Russian parts :-) Am I right in assuming that this is a grey area in  general and nobody on the team is currently fully familiar with the connection from and to lokalise? No offence meant, I was loosely following the past development around HC and I am aware that this could never have been top priority. Could you tell me where you triggered last time? And is there somebody else I could get more information from? And yes, you can give me more power, I will  try what I can. You should find me under "Ewald Arnold" or maybe just Ewald.

Is there already some documentation around the process from the past 2 days? Or is there some agreed place to put such doc files? If not, I could collect my findings in a README.md in webapp/locales. I am also a firm believer in documentation ;-)

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-11-04T22:13:27Z" title="Monday, November 4th 2019, 11:13:27 pm +01:00">Nov 4, 2019</time>_

---


@ewanold we have triggered a `download` today multiple times and were discussing with @Mogge about inconsistencies and ways we can get better in the future.

The thing is that no one on the team was too up-to-date or concerned with `Lokalise` cause we didn't have anyone in the community that was looking to use it to add translations. Now that we do have interest, we need to manage it together.

Between those of us willing to help out, we need to trigger these downloads to sync `Lokalise` with the `.json` files in our `repo`

Then, we need to check that there aren't missing keys, which there were quite a few today.

Also, if any of the developers change the layout of the `.json` structure, they need to also delete obsolete keys from `Lokalise`; otherwise, we will end up with the missing keys :point_up: and potentially have translators putting in time for keys that have been changed and are then obsolete.

Finally, we need to hold other developers accountable and remind them that if they change the structure of `.json` files, they need to update `Lokalise`, as described :point_up_2:

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-11-04T23:54:52Z" title="Tuesday, November 5th 2019, 12:54:52 am +01:00">Nov 5, 2019</time>_

---


@ewanold you are now an admin user. Apparently you use a catchall address and you have three emails at lokalise. I used your email address starting with `lokalise@`

I would absolutely :heart: if you could add documentation for lokalise.

**Comment by Tirokk** [comment]
> [vbelolapotkov](https://github.com/vbelolapotkov) **Authored by [vbelolapotkov](https://github.com/vbelolapotkov)**
_<time datetime="2019-11-05T11:27:48Z" title="Tuesday, November 5th 2019, 12:27:48 pm +01:00">Nov 5, 2019</time>_

---


@roschaefer @ewanold I've checked it locally and it works taking into account that most of the translations are missing at the moment :)

**Comment by Tirokk** [comment]
> [ewanold](https://github.com/ewanold) **Authored by [ewanold](https://github.com/ewanold)**
_<time datetime="2019-11-05T17:51:46Z" title="Tuesday, November 5th 2019, 6:51:46 pm +01:00">Nov 5, 2019</time>_

---


@vbelolapotkov @Mogge @mattwr18 

> I would absolutely heart if you could add documentation for lokalise.

Just FYI: I started a new branch for docs and new lokalise related stuff at 

https://github.com/Human-Connection/Human-Connection/tree/lokalise-automation/webapp/locales

**Comment by Tirokk** [comment]
> [ewanold](https://github.com/ewanold) **Authored by [ewanold](https://github.com/ewanold)**
_<time datetime="2019-11-06T08:17:04Z" title="Wednesday, November 6th 2019, 9:17:04 am +01:00">Nov 6, 2019</time>_

---


> we have triggered a `download` today multiple times

I assume this did not succeed? At least I could not find a ru.json anywhere. I added the most recent ru.json to this PR. Hope this helps :-)

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-11-06T11:34:02Z" title="Wednesday, November 6th 2019, 12:34:02 pm +01:00">Nov 6, 2019</time>_

---


> > we have triggered a `download` today multiple times
> 
> I assume this did not succeed? At least I could not find a ru.json anywhere. I added the most recent ru.json to this PR. Hope this helps :-)

I think it wasn't clear what I meant, or maybe you are right and it didn't work... when I say we triggered a `download` today, I meant that from `Lokalise` if you trigger a download, you grab the latest from our `master` branch in this repo for others to translate there.

**Comment by Tirokk** [comment]
> [ewanold](https://github.com/ewanold) **Authored by [ewanold](https://github.com/ewanold)**
_<time datetime="2019-11-06T12:44:28Z" title="Wednesday, November 6th 2019, 1:44:28 pm +01:00">Nov 6, 2019</time>_

---


> I think it wasn't clear what I meant, or maybe you are right and it didn't work... when I say we 

divided by a common language :-/ I thought you meant to download *from* lokalise to github as ru.json has not yet appeared anywhere from my point of view.

> Could you please put in a separate PR with these changes?

Have I unintentionally introduced junk when changing branches? This is actually the first time I am doing more complicated things than pull or push... though I am not aware having seen  any of the files above. I only worked below webapp/locales.

**Comment by Tirokk** [comment]
> [ewanold](https://github.com/ewanold) **Authored by [ewanold](https://github.com/ewanold)**
_<time datetime="2019-11-07T17:47:44Z" title="Thursday, November 7th 2019, 6:47:44 pm +01:00">Nov 7, 2019</time>_

---


> Then, we need to check that there aren't missing keys,
@Mogge 

I might be missing something, but how about collecting all the keys from the sources and verifying these against all json files, especially en.json? I already talked about this with someone on discord who claimed en.json was guaranteed to always be correct. Is this really always the case? 

If you had problems in this regard in the past, you might consider something like the script I cobbled together. It scans js and vue files for calls to $t().  It misses a lot currently, but it shows the intent. Based on those keys we could verify the json files.

https://github.com/Human-Connection/Human-Connection/blob/lokalise-automation/webapp/locales/bin/gettrans.sh

**Comment by Tirokk** [comment]
> [vbelolapotkov](https://github.com/vbelolapotkov) **Authored by [vbelolapotkov](https://github.com/vbelolapotkov)**
_<time datetime="2019-11-10T08:52:52Z" title="Sunday, November 10th 2019, 9:52:52 am +01:00">Nov 10, 2019</time>_

---


@ewanold I've synced the branch with master to remove unrelated changes from review. Now changes look better.

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-11-11T09:02:13Z" title="Monday, November 11th 2019, 10:02:13 am +01:00">Nov 11, 2019</time>_

---


can we merge this in @ewanold @vbelolapotkov ??

**Comment by Tirokk** [comment]
> [ewanold](https://github.com/ewanold) **Authored by [ewanold](https://github.com/ewanold)**
_<time datetime="2019-11-11T09:59:35Z" title="Monday, November 11th 2019, 10:59:35 am +01:00">Nov 11, 2019</time>_

---


> can we merge this in @ewanold @vbelolapotkov ??

Yes,  the translations are good enough to start and we are eager to see the website to improve things if needed.

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-11-11T13:38:38Z" title="Monday, November 11th 2019, 2:38:38 pm +01:00">Nov 11, 2019</time>_

---


Great!! Really appreciate it :green_heart:

**Comment by Tirokk** [comment]
> [ewanold](https://github.com/ewanold) **Authored by [ewanold](https://github.com/ewanold)**
_<time datetime="2019-11-11T15:16:50Z" title="Monday, November 11th 2019, 4:16:50 pm +01:00">Nov 11, 2019</time>_

---


> Great!! Really appreciate it 

The pleasure is all on my side - and I assume @vbelolapotkov feels similar.
I do hope Human Connection can contribute and help better connect fellow human beings from the west and the east, we are all Menschheitsfamilie  :-)

**Review by Mogge — APPROVED** [review]

**Pull request closed without merging**
