### PR TITLE
[WIP] [Don't Merge] Add tests to expose bug

### LINKED ISSUE #542: 🐛 Rapidly double clicking on `Comment` button causes two database writes
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-05-05T15:44:47Z" title="Sunday, May 5th 2019, 5:44:47 pm +02:00">May 5, 2019</time>_
_Closed <time datetime="2019-06-04T16:38:18Z" title="Tuesday, June 4th 2019, 6:38:18 pm +02:00">Jun 4, 2019</time>_
---

## :bug: Bugreport

At the moment, if you rapidly click on the `Comment` button, it is possible to create multiple comments with the same content.

Currently, in the `handleSubmit` method, the button is disabled and set to loading, but it is still possible to fire two events before the button is disabled and apollo is sending two requests.
Screenshot at 2019-05-05 12:33:22

### Steps to reproduce the behavior
1. visit `/`
2. click on a post
3. write a comment
4. click rapidly twice on the `Comment` button

### Expected behavior

There should be some way of handling this situation, if a user wants to comment the same thing twice, for whatever reason, they should need to type the same message/copy && paste it.

More often than not, this will happen by accident, and therefore we should have some protection against this.

have found this https://github.com/Akryum/vue-apollo/issues/185
 which suggests that adding `optimisticResponse` prevents two database writes https://github.com/Akryum/vue-apollo/issues/185#issuecomment-364696038

I've yet to successfully test this in favor of opening a new issue to explore options

### Version & Environment
 Type: []      
 - OS: []      
 - Browser: [] 
 - Version []  
 - Device: []

### PR DESCRIPTION
**Pull request by Tirokk**
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-05-07T14:14:50Z" title="Tuesday, May 7th 2019, 4:14:50 pm +02:00">May 7, 2019</time>_
_Closed <time datetime="2019-06-04T16:37:18Z" title="Tuesday, June 4th 2019, 6:37:18 pm +02:00">Jun 4, 2019</time>_
---

- clicking on the "Comment" button twice

### Issues

- fixes #542

### CODE REVIEW

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-05-13T13:03:54Z" title="Monday, May 13th 2019, 3:03:54 pm +02:00">May 13, 2019</time>_

---


@ulfgebhardt @Tirokk @roschaefer 
In regards to this `PR`, I was trying to replicate the double creation of comments bug on https://nitro-staging.human-connection.org and was unable to.

I wonder if more time should be spent trying to fix this bug, if it appears to be only a problem in a dev env(?). If you all still thinks it's worth spending time on, I think I have fixed the bug by using lodash's `debounce`, but the unit tests are now broken, and need to be debugged.

So, repeating my question from `Discord`, how do people feel about the fix?

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-05-13T14:57:47Z" title="Monday, May 13th 2019, 4:57:47 pm +02:00">May 13, 2019</time>_

---


ok, so then are you suggesting to debug the component tests and how to get them passing with lodash's `debounce`, or should we be only dealing with bugs reproducible on `nitro-staging`/`nitro-master`?

**Comment by Tirokk** [comment]
> [codecov[bot]](https://github.com/apps/codecov) **Authored by [codecov[bot]](https://github.com/apps/codecov)**
_<time datetime="2019-05-13T17:33:25Z" title="Monday, May 13th 2019, 7:33:25 pm +02:00">May 13, 2019</time>_

---


# [Codecov](https://codecov.io/gh/Human-Connection/Human-Connection/pull/561?src=pr&el=h1) Report
> Merging [#561](https://codecov.io/gh/Human-Connection/Human-Connection/pull/561?src=pr&el=desc) into [master](https://codecov.io/gh/Human-Connection/Human-Connection/commit/74109256b23753568baecf633a850542687650da?src=pr&el=desc) will **decrease** coverage by `0.01%`.
> The diff coverage is `33.33%`.

[Impacted file tree graph](https://codecov.io/gh/Human-Connection/Human-Connection/pull/561?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #561      +/-   ##
==========================================
- Coverage   20.15%   20.14%   -0.01%     
==========================================
  Files         157      157              
  Lines        2208     2214       +6     
  Branches      105      107       +2     
==========================================
+ Hits          445      446       +1     
- Misses       1739     1743       +4     
- Partials       24       25       +1
```


| [Impacted Files](https://codecov.io/gh/Human-Connection/Human-Connection/pull/561?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [webapp/components/comments/CommentForm/index.vue](https://codecov.io/gh/Human-Connection/Human-Connection/pull/561/diff?src=pr&el=tree#diff-d2ViYXBwL2NvbXBvbmVudHMvY29tbWVudHMvQ29tbWVudEZvcm0vaW5kZXgudnVl) | `69.23% <33.33%> (-15.77%)` | :arrow_down: |

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-05-13T20:05:39Z" title="Monday, May 13th 2019, 10:05:39 pm +02:00">May 13, 2019</time>_

---


@mattwr18 I don't even believe that this error only happens on `development`. What I mean is: I don't really like this workaround but it is :ok: for me. It feels like treating symptoms instead of treating the cause of the disease.

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-05-29T12:06:39Z" title="Wednesday, May 29th 2019, 2:06:39 pm +02:00">May 29, 2019</time>_

---


@mattwr18 any updates on this?

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-05-29T12:14:15Z" title="Wednesday, May 29th 2019, 2:14:15 pm +02:00">May 29, 2019</time>_

---


the update is that I am still unclear whether we should be adding code to deal with a bug that we haven't been able to reproduce in a deployed environment.
I guess maybe what you are saying is just merge in the latest changes and let's get it merged in anyways?

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-06-01T01:21:57Z" title="Saturday, June 1st 2019, 3:21:57 am +02:00">Jun 1, 2019</time>_

---


that is what I would be in favor of @roschaefer... the work won't be lost if we ever need this solution, we can always reopen, or copy and paste the solution... it's just that I think I jumped the gun and created an issue that wasn't actually an issue for our user base.

what do you think @Tirokk?

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-06-04T16:37:18Z" title="Tuesday, June 4th 2019, 6:37:18 pm +02:00">Jun 4, 2019</time>_

---


I believe we are all more or less in agreement on this @Tirokk @roschaefer 
and it's not that the decision to close this now will mean we can never use this code if we find that I am wrong and the user base does experience this issue...

**Review by Mogge — APPROVED** [review]
@mattwr18 I give this PR my approval even though I am not happy with it. It feels like a workaround. It would be desirable to learn what the cause of the error is. Could it be the styleguide not disabling the button maybe?

I find this approach practicable if we can't help us in another way.

**Review by Mogge — CHANGES_REQUESTED** [review]
On our build server, `yarn run lint` fails and one of the webapp test. Could you fix that? Before you do that, could you also resolve the merge conflicts?

**Pull request closed without merging**
