### PR TITLE
🍰 Update follower count on follow/unfollow

### LINKED ISSUE #293: Follower count in floating window above user links does not increase
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2019-03-06T15:07:31Z" title="Wednesday, March 6th 2019, 4:07:31 pm +01:00">Mar 6, 2019</time>_
_Closed <time datetime="2019-09-11T10:33:57Z" title="Wednesday, September 11th 2019, 12:33:57 pm +02:00">Sep 11, 2019</time>_
---

**Describe the bug**
The followers count does not increase. See screenshots …

**To Reproduce**
- If you are in a post of somebody else …
- You hover over the link of the author …
- A floating window appears with the counts of the followers and the counts of his or her posts etc. …
- You are a non follower and click on *following* …

**Expected behavior**
- The followers count does increase.

**Screenshots**
bildschirmfoto 2019-03-06 um 15 14 06
bildschirmfoto 2019-03-06 um 15 14 16

**Desktop (please complete the following information):**
 - macOS FireFox

**Additional context**
Related to old issue #213 .

### PR DESCRIPTION
**Pull request by Tirokk**
> [vbelolapotkov](https://github.com/vbelolapotkov) **Authored by [vbelolapotkov](https://github.com/vbelolapotkov)**
_<time datetime="2019-09-09T07:06:07Z" title="Monday, September 9th 2019, 9:06:07 am +02:00">Sep 9, 2019</time>_
_Merged <time datetime="2019-09-11T10:33:57Z" title="Wednesday, September 11th 2019, 12:33:57 pm +02:00">Sep 11, 2019</time>_
---

## 🍰 Pullrequest
A quick fix to update followedByCount of a followed/unfollowed user in pop up.

### Issues
- fixes #293 

### Todo
- [ ] Update schema and mutation

### CODE REVIEW

**Comment by Tirokk** [comment]
> [vbelolapotkov](https://github.com/vbelolapotkov) **Authored by [vbelolapotkov](https://github.com/vbelolapotkov)**
_<time datetime="2019-09-09T07:12:28Z" title="Monday, September 9th 2019, 9:12:28 am +02:00">Sep 9, 2019</time>_

---


IMO follow/unfollow mutation need to be updated to return more than just boolean result, but followed node as well.
Currently, on a user page, the user query is triggered every time when follow/unfollow is clicked. This can be avoided as well if follow/unfollow mutation can return followed user.

**Comment by Tirokk** [comment]
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2019-09-09T14:23:35Z" title="Monday, September 9th 2019, 4:23:35 pm +02:00">Sep 9, 2019</time>_

---


Hey @vbelolapotkov ,

I had a short overlook and functionally check. 😎🚀
Wonderful quick solution. 🤗

And, because you have the unchecked todo and didn't requested a review, I added the WIP in front of the PR title.

**Comment by Tirokk** [comment]
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2019-09-11T06:05:59Z" title="Wednesday, September 11th 2019, 8:05:59 am +02:00">Sep 11, 2019</time>_

---


If you think @vbelolapotkov this is ready for a review then remove the [WIP] (work in progress). 🤗

**Comment by Tirokk** [comment]
> [vbelolapotkov](https://github.com/vbelolapotkov) **Authored by [vbelolapotkov](https://github.com/vbelolapotkov)**
_<time datetime="2019-09-11T07:07:10Z" title="Wednesday, September 11th 2019, 9:07:10 am +02:00">Sep 11, 2019</time>_

---


@Tirokk as a quick fix it's ready for review but it leads to weird counter transitions on a user page. 
I have suggested a solution above and I'd like to get your feedback on it as it will take time to implement. 
Probably the best solution is to review and merge quick fix, then create a new ticket for further improvement.

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-09-11T10:34:37Z" title="Wednesday, September 11th 2019, 12:34:37 pm +02:00">Sep 11, 2019</time>_

---


Thank you @vbelolapotkov you rock :guitar: :metal:

**Comment by Tirokk** [comment]
> [vbelolapotkov](https://github.com/vbelolapotkov) **Authored by [vbelolapotkov](https://github.com/vbelolapotkov)**
_<time datetime="2019-09-11T10:36:15Z" title="Wednesday, September 11th 2019, 12:36:15 pm +02:00">Sep 11, 2019</time>_

---


@roschaefer, thanks! Anyways, I'd like to update the resolvers as part of new issue. I'll create one tmw.

**Review by Mogge — APPROVED** [review]
@vbelolapotkov good catch!

I totally agree with you that `follow` and `unfollow` should return the updated user. The corresponding resolver was implemented before we learned how to do it without `neo4j-graphql-js`.

And I'm willing to merge this in and refactor later.

quickfix

**Pull request closed without merging**
