### PR TITLE
Fix translation error

### LINKED ISSUE #1874: 🐛 [Bug] Login page translation error DE
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2019-10-11T10:36:00Z" title="Friday, October 11th 2019, 12:36:00 pm +02:00">Oct 11, 2019</time>_
_Closed <time datetime="2019-10-13T06:45:23Z" title="Sunday, October 13th 2019, 8:45:23 am +02:00">Oct 13, 2019</time>_
---

## :bug: Bugreport

Login page translation error DE.

### Steps to reproduce the behavior
1. go to login page
2. see here

Bildschirmfoto 2019-10-11 um 12 19 21

### PR DESCRIPTION
**Pull request by Tirokk**
> [janethavi](https://github.com/janethavi) **Authored by [janethavi](https://github.com/janethavi)**
_<time datetime="2019-10-12T07:15:48Z" title="Saturday, October 12th 2019, 9:15:48 am +02:00">Oct 12, 2019</time>_
_Closed <time datetime="2019-10-14T05:07:30Z" title="Monday, October 14th 2019, 7:07:30 am +02:00">Oct 14, 2019</time>_
---

## 🍰 Pullrequest
Fix translation error in Deutsch.

### Issues
- fixes #1874

### CODE REVIEW

**Comment by Tirokk** [comment]
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2019-10-12T11:04:05Z" title="Saturday, October 12th 2019, 1:04:05 pm +02:00">Oct 12, 2019</time>_

---


I asked on Discord to give you permission …
But the branch build was not reported at all, so you could try to push it here again to trigger the build …

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-10-12T17:45:55Z" title="Saturday, October 12th 2019, 7:45:55 pm +02:00">Oct 12, 2019</time>_

---


@janethavi you have been accepted to our `Volunteers` team, please accept the invitation.
Sorry, but we have encrypted environment variables, and Travis does not allow access to these from forks... see https://docs.travis-ci.com/user/environment-variables/#encrypting-environment-variables for their explanation as to why.
As @Tirokk said, could you please push directly to the `Human-Connection` repository?

**Comment by Tirokk** [comment]
> [janethavi](https://github.com/janethavi) **Authored by [janethavi](https://github.com/janethavi)**
_<time datetime="2019-10-13T04:07:55Z" title="Sunday, October 13th 2019, 6:07:55 am +02:00">Oct 13, 2019</time>_

---


Hi @mattwr18 @Tirokk 
Please find the new branch in:
https://github.com/Human-Connection/Human-Connection/tree/1874-fix
Thank you :)

**Review by Mogge — APPROVED** [review]
Well done and a good start @janethavi !!! 💫

Thanks for your contribution! 🙏🏼🚀

PS: I know the build has not passed. And I have a clue why …
Please push your branch directly to the original Human Connection repository @janethavi otherwise the build of your PR fails.
I know you need permission @janethavi (Please care for that @ogerly @mattwr18 @roschaefer ). I could not do give you permission in other cases.

**Pull request closed without merging**
