### PR TITLE
Revert logout.vue

### PR DESCRIPTION
**Pull request by Tirokk**
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-05-10T13:40:49Z" title="Friday, May 10th 2019, 3:40:49 pm +02:00">May 10, 2019</time>_
_Merged <time datetime="2019-05-13T10:40:02Z" title="Monday, May 13th 2019, 12:40:02 pm +02:00">May 13, 2019</time>_
---

For any static image URL we don't need to use `<hc-image>`. The assets
will be served from the frontend container. I did not anticipate that we
have a lot of static images in the frontend when I said "You can replace
every image with the `<hc-image>` component".

@aonomike: In the future you can make some screenshots and post them in the PR
and ask for help.

@ulfgebhardt: Yes, it would have been safer not to merge the PR. We
might run into the danger of forgetting things like this.

### Issues

- [X] None

### Checklist

- [X] None

### How2Test

- [X] None

### Todo

- [X] None

### CODE REVIEW

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-05-10T17:07:22Z" title="Friday, May 10th 2019, 7:07:22 pm +02:00">May 10, 2019</time>_

---


Is there no way to take a screenshot of this @roschaefer?
It seems to me that this `webapp/pages/logout.vue` gets called when someone visits `/logout`, or clicks on the `Logout` link in the `Dropdown`, but the image appears so quickly before being redirected to `/login` that it's difficult to take a screen shot....

Actually, I just commented out `this.$router.replace('/')` from line 42 of logout.vue and caught this beautiful shot
Screenshot at 2019-05-10 14:05:49

**Comment by Tirokk** [comment]
> [codecov[bot]](https://github.com/apps/codecov) **Authored by [codecov[bot]](https://github.com/apps/codecov)**
_<time datetime="2019-05-10T17:27:54Z" title="Friday, May 10th 2019, 7:27:54 pm +02:00">May 10, 2019</time>_

---


# [Codecov](https://codecov.io/gh/Human-Connection/Human-Connection/pull/594?src=pr&el=h1) Report
> Merging [#594](https://codecov.io/gh/Human-Connection/Human-Connection/pull/594?src=pr&el=desc) into [master](https://codecov.io/gh/Human-Connection/Human-Connection/commit/fe386e235581faf06929604e4addac313bed0b99?src=pr&el=desc) will **increase** coverage by `0.02%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/Human-Connection/Human-Connection/pull/594?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #594      +/-   ##
==========================================
+ Coverage   20.14%   20.15%   +0.02%     
==========================================
  Files         157      157              
  Lines        2210     2208       -2     
  Branches      105      105              
==========================================
  Hits          445      445              
+ Misses       1741     1739       -2     
  Partials       24       24
```


| [Impacted Files](https://codecov.io/gh/Human-Connection/Human-Connection/pull/594?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [webapp/pages/logout.vue](https://codecov.io/gh/Human-Connection/Human-Connection/pull/594/diff?src=pr&el=tree#diff-d2ViYXBwL3BhZ2VzL2xvZ291dC52dWU=) | `0% <ø> (ø)` | :arrow_up: |

**Review by Mogge — APPROVED** [review]
great! not likely the user will see this as they are redirected so quickly to login, but doesn't mean it should be left broken!! good job @roschaefer

**Review by Mogge — APPROVED** [review]
LGTM...thanks @roschaefer

**Review by Mogge — APPROVED** [review]
LGTM...thanks @roschaefer

**Pull request closed without merging**
