### PR TITLE
Lokalise: Translations update

### PR DESCRIPTION
**Pull request by Tirokk**
> [appinteractive](https://github.com/appinteractive) **Authored by [appinteractive](https://github.com/appinteractive)**
_<time datetime="2019-11-18T20:34:01Z" title="Monday, November 18th 2019, 9:34:01 pm +01:00">Nov 18, 2019</time>_
_Closed <time datetime="2019-11-20T12:07:49Z" title="Wednesday, November 20th 2019, 1:07:49 pm +01:00">Nov 20, 2019</time>_
---

This pull request was initiated by Lokalise (user Mogge) at 2019-11-18 21:33:48

### CODE REVIEW

**Comment by Tirokk** [comment]
> [Mogge](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2019-11-18T22:22:31Z" title="Monday, November 18th 2019, 11:22:31 pm +01:00">Nov 18, 2019</time>_

---


Please check if Russian has the appropriate file name now.

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-11-18T22:30:12Z" title="Monday, November 18th 2019, 11:30:12 pm +01:00">Nov 18, 2019</time>_

---


@Mogge you can merge this once the build server has passed.

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2019-11-19T01:48:11Z" title="Tuesday, November 19th 2019, 2:48:11 am +01:00">Nov 19, 2019</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/#/projects/qa7fe2/runs/2172/specs"></a> <b title="Passed">48</b>  &bull; <a href="https://dashboard.cypress.io/#/projects/qa7fe2/runs/2172/failures"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | 6785b47353 |
| **Started** | Nov 19, 2019 1:37 AM |
| **Ended** | Nov 19, 2019 1:52 AM |
| **Duration** | 14:46 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Chromium 78  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/#/projects/qa7fe2/runs/2172/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/#/projects/qa7fe2/settings)

**Review by Mogge — APPROVED** [review]
Russia

**Pull request closed without merging**
