### PR TITLE
feat: German Translation Update By Andreas Plank

### PR DESCRIPTION
**Pull request by Tirokk**
> [human-connection-release-bot](https://github.com/human-connection-release-bot) **Authored by [human-connection-release-bot](https://github.com/human-connection-release-bot)**
_<time datetime="2020-01-24T13:45:16Z" title="Friday, January 24th 2020, 2:45:16 pm +01:00">Jan 24, 2020</time>_
_Closed <time datetime="2020-02-18T17:41:03Z" title="Tuesday, February 18th 2020, 6:41:03 pm +01:00">Feb 18, 2020</time>_
---

This pull request was initiated by Lokalise (user Mogge) at 2020-01-24 14:45:12

### CODE REVIEW

**Comment by Tirokk** [comment]
> [Mogge](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2020-01-24T13:47:59Z" title="Friday, January 24th 2020, 2:47:59 pm +01:00">Jan 24, 2020</time>_

---


I will check this in Detail later, as the keys are sorted alphabetically.

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-01-24T14:15:35Z" title="Friday, January 24th 2020, 3:15:35 pm +01:00">Jan 24, 2020</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/4599/specs"></a> <b title="Passed">53</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/4599/failures"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | 904f275458 |
| **Started** | Jan 28, 2020 11:16 PM |
| **Ended** | Jan 28, 2020 11:31 PM |
| **Duration** | 14:51 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Electron 78  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/4599/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings)

**Comment by Tirokk** [comment]
> [Mogge](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2020-01-28T22:26:58Z" title="Tuesday, January 28th 2020, 11:26:58 pm +01:00">Jan 28, 2020</time>_

---


I cross checked all keys. Changes made by the muted-users feature are integrated. The changes made by Andreas Plank are great. Correct German quotation marks, better German expressions, etc.

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2020-01-30T00:56:45Z" title="Thursday, January 30th 2020, 1:56:45 am +01:00">Jan 30, 2020</time>_

---


@Mogge why? It's fine if these PRs get merge conflicts. I was about to hit "merge" but your last comment stopped me from doing so.

**Comment by Tirokk** [comment]
> [Mogge](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2020-02-18T17:41:03Z" title="Tuesday, February 18th 2020, 6:41:03 pm +01:00">Feb 18, 2020</time>_

---


I will import this translations again. We have escaped slashes in the import.

**Review by Mogge — APPROVED** [review]
As mentioned before. New keys in master are present. Obsolete keys are kicked. The changes made are all improvements

**Pull request closed without merging**
