### PR TITLE
fix(webapp): Remove websockets to deploy security hot fix

### LINKED ISSUE #3082: 💥 [DevOps] Remove wsEndpoint to unblock deployment
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2020-02-17T11:28:44Z" title="Monday, February 17th 2020, 12:28:44 pm +01:00">Feb 17, 2020</time>_
_Closed <time datetime="2020-02-26T09:35:52Z" title="Wednesday, February 26th 2020, 10:35:52 am +01:00">Feb 26, 2020</time>_
---

## :fire: DevOps ticket

At the moment, we have an issue with deploying websockets due to ability to configure websockets_uri for different production environments. See https://github.com/Human-Connection/Human-Connection/issues/3064 and https://github.com/nuxt/nuxt.js/issues/5100

This is blocking our deployment of other features/bug fixes, but most importantly a security related bug fix. If we remove the `wsEndpoint`, it will not try to connect to websockets and we can work on a solution.
### Motive

see :point_up_2: 
### Related issues

see :point_up_2: 
### Implementation

comment out the line in `apollo-config.js`
### Validation

when it's deployed and does not try to connect to websockets, it should be considered successful.

### PR DESCRIPTION
**Pull request by Tirokk**
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2020-02-17T11:29:12Z" title="Monday, February 17th 2020, 12:29:12 pm +01:00">Feb 17, 2020</time>_
_Closed <time datetime="2020-02-17T23:28:56Z" title="Tuesday, February 18th 2020, 12:28:56 am +01:00">Feb 18, 2020</time>_
---

## 🍰 Pullrequest

Did not 
### Issues

- fixes #3082

### CODE REVIEW

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-02-17T11:59:42Z" title="Monday, February 17th 2020, 12:59:42 pm +01:00">Feb 17, 2020</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/5186/specs"></a> <b title="Passed">61</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/5186/failures"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | 9631190e9d |
| **Started** | Feb 17, 2020 12:38 PM |
| **Ended** | Feb 17, 2020 12:52 PM |
| **Duration** | 13:41 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Electron 78  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/5186/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings)

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2020-02-17T14:00:13Z" title="Monday, February 17th 2020, 3:00:13 pm +01:00">Feb 17, 2020</time>_

---


no, we don't
do you think that is acceptable for a week, or so?

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2020-02-17T15:11:55Z" title="Monday, February 17th 2020, 4:11:55 pm +01:00">Feb 17, 2020</time>_

---


it might not be difficult actually @Tirokk

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2020-02-17T18:18:38Z" title="Monday, February 17th 2020, 7:18:38 pm +01:00">Feb 17, 2020</time>_

---


@mattwr18 yes, shall we merge?

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2020-02-17T18:26:49Z" title="Monday, February 17th 2020, 7:26:49 pm +01:00">Feb 17, 2020</time>_

---


It's failing the build... I added back the poll notifications and it was throwing a `Subscription.notificationAdded returned undefined` error

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2020-02-17T23:28:56Z" title="Tuesday, February 18th 2020, 12:28:56 am +01:00">Feb 18, 2020</time>_

---


Closing since @roschaefer fixed our next build/runtime env variables!!!

**Review by Mogge — APPROVED** [review]
> did not
What? @mattwr18 

This looks good to me. Do we still have the polling notifications?

**Review by Mogge — APPROVED** [review]
It’s not so nice in my eyes to have no pulling.
And the people don’t know that they have to reload the page.
On the other hand I understand that it is not so easy to revert this.
Therefore I do approve.
But will look like a bug to the users …

**Pull request closed without merging**
