### PR TITLE
Terms of use extended with dot - no commercial use

### LINKED ISSUE #2170: 🚀 [Feature] Change of Terms of Service
> [datenbrei](https://github.com/datenbrei) **Authored by [datenbrei](https://github.com/datenbrei)**
_<time datetime="2019-11-08T16:18:16Z" title="Friday, November 8th 2019, 5:18:16 pm +01:00">Nov 8, 2019</time>_
_Closed <time datetime="2019-12-02T12:10:59Z" title="Monday, December 2nd 2019, 1:10:59 pm +01:00">Dec 2, 2019</time>_
---

## :rocket: Feature
The ToS is to be extended after point "6. Fehler und Feedback:" Addition: 

Keine kommerzielle Nutzung

Die Nutzung des Human Connection Netzwerkes ist nicht gestattet für kommerzielle Nutzung. Darunter fällt unter anderem das Bewerben von Produkten mit kommerzieller Absicht, das Einstellen von Affiliate-Links, direkter Aufruf zu Spenden oder finanzieller Unterstützung für Zwecke, die steuerlich nicht als gemeinnützig anerkannt sind. 

### User Problem
Up to now it is not totally clear, what is allowd and what is not allowed, if we talk about commercial use.

### Implementation
Just change the ToS text. Shift all following numbers 

### Design & Layout
---

### Validation
not needed

### PR DESCRIPTION
**Pull request by Tirokk**
> [ogerly](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-11-21T09:20:50Z" title="Thursday, November 21st 2019, 10:20:50 am +01:00">Nov 21, 2019</time>_
_Merged <time datetime="2019-12-02T12:10:59Z" title="Monday, December 2nd 2019, 1:10:59 pm +01:00">Dec 2, 2019</time>_
---

## 🍰 Pullrequest
Terms of use extended with dot - no commercial use

### Issues
- fixes #2170 

# deutsch
FireShot Capture 002 - Nutzungsbedingungen - Human Connection - localhost

# english
FireShot Capture 003 - Terms and conditions - Human Connection - localhost

### CODE REVIEW

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2019-11-21T11:05:51Z" title="Thursday, November 21st 2019, 12:05:51 pm +01:00">Nov 21, 2019</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/2657/specs"></a> <b title="Passed">48</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/2657/failures"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | 8ec5922326 |
| **Started** | Dec 5, 2019 7:46 PM |
| **Ended** | Dec 5, 2019 8:01 PM |
| **Duration** | 14:36 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Chromium 78  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/2657/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings)

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-11-22T09:57:55Z" title="Friday, November 22nd 2019, 10:57:55 am +01:00">Nov 22, 2019</time>_

---


@alina-beck can we work on the layout together? I feel lost when it comes to the `MasonryGrid`, I could study up on it, but I'd love to use it as an excuse to pair with you, and I think it's ready...
I'm sure there is probably code that needs to be deleted that I added to the frontend, but I think I am fetching the data you wanted `imageAspectRatio`, setting it for new images added, and updating all the `Post` that have images in the database- this needs to be tested on `develop` and `nitro-staging` though.

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-12-02T08:52:09Z" title="Monday, December 2nd 2019, 9:52:09 am +01:00">Dec 2, 2019</time>_

---


Just having a look at this @alina-beck ... at the very end of the scroll, when there are no posts left... I'm seeing this..
Screenshot from 2019-12-02 09-51-27

**Comment by Tirokk** [comment]
> [alina-beck](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2019-12-02T13:24:42Z" title="Monday, December 2nd 2019, 2:24:42 pm +01:00">Dec 2, 2019</time>_

---


@mattwr18 I updated the seed data so that the `imageAspectRatio` corresponds with the actual image size – now it looks good! :wink:

**Comment by Tirokk** [comment]
> [alina-beck](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2019-12-04T09:49:56Z" title="Wednesday, December 4th 2019, 10:49:56 am +01:00">Dec 4, 2019</time>_

---


@roschaefer @mattwr18 the masonry grid solution we were using is exactly the one proposed here: https://w3bits.com/css-grid-masonry/ :wink:

The issue with this (as well as the [masonry package](https://masonry.desandro.com/layout.html) – see `imagesLoaded`) is that it first calculates the size of each item in the grid, _then_ the images get loaded, _then_ it needs to recalculate the size which makes the layout jump.

The solution we came up with in this PR is storing an `imageAspectRatio` in the database and using this (instead of waiting for the actual image) to calculate the size of the post cards.

But there's another catch: Before the `PostCards` are finished rendering with their correct size the `MasonryGridItems` are already displayed. And if their `rowSpan` (i.e. height) is set to `0` you see this for a second:
Screenshot 2019-12-04 at 12 31 43

So what I did is pass the `imageAspectRatio` directly to the `MasonryGridItem` to _estimate_ the space needed for the `PostCard` and avoid big jumps in the layout when (a moment later) the `PostCard` has finished rendering – and this is where my (practically non-existent) math skills fail me:

For a width of `300`...
- an aspect ratio of `2` means a height of `150`
- an aspect ratio of `1.5` means a height of `200`
- an aspect ratio of `1` means a height of `300`
- an aspect ratio of `0.5` means a height of `600`
- and with an aspect ratio of `0.2` we land at a height of `1.500`

So it's not a linear relation – I can't just say for each `.5` change add `2` rows to the height. I'm sure there is some kind of formula that would allow us to do this more accurately than having 3 fixed ratios to compare to, like I did above, but it will always be an estimation at this point because we don't yet have the actual `width` to calculate with. So unless one of you has such a formula up their sleeves I'd say let's give this solution a go? :grin:

PS: I'll try to improve the tests before we merge!

**Review by Mogge — CHANGES_REQUESTED** [review]
ratio

Looks good but could be improved :+1:

**Review by Mogge — APPROVED** [review]

**Pull request closed without merging**
