### PR TITLE
Update to 0.1.2

### PR DESCRIPTION
**Pull request by Tirokk**
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-10-01T11:55:04Z" title="Tuesday, October 1st 2019, 1:55:04 pm +02:00">Oct 1, 2019</time>_
_Merged <time datetime="2019-10-02T16:33:14Z" title="Wednesday, October 2nd 2019, 6:33:14 pm +02:00">Oct 2, 2019</time>_
---

Version bump

### CODE REVIEW

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-10-01T16:19:24Z" title="Tuesday, October 1st 2019, 6:19:24 pm +02:00">Oct 1, 2019</time>_

---


I'm not sure why the `CHANGELOG` is merged... it's how the tool `github_changelog_generator` works, I guess.. I would prefer it the way you suggest as well, makes it much easier to see what was changed when... I'll have a look at the docs and see if there are flags that give us the desired output...

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-10-01T21:48:06Z" title="Tuesday, October 1st 2019, 11:48:06 pm +02:00">Oct 1, 2019</time>_

---


@mattwr18 
```
rm CHANGELOG.md
git-generate-changelog --some --params --since-tag 0.1.1
```
Maybe?

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-10-01T22:07:05Z" title="Wednesday, October 2nd 2019, 12:07:05 am +02:00">Oct 2, 2019</time>_

---


I could give it a go @roschaefer

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-10-02T11:04:33Z" title="Wednesday, October 2nd 2019, 1:04:33 pm +02:00">Oct 2, 2019</time>_

---


tried that out, and it gave the same output as before @roschaefer

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-10-02T16:33:11Z" title="Wednesday, October 2nd 2019, 6:33:11 pm +02:00">Oct 2, 2019</time>_

---


ok, I updated the release with the diff... but I guess I need to generate this directly before deploying the latest changes, not the day before cause there were a few `PR`s merged in that happened after this was generated

**Review by Mogge — CHANGES_REQUESTED** [review]
Why is the Changelog merged? I would prefer to have all the bugs and features grouped by version.

Also, please write the changelog into your commit message. I tried to implement the automatic github release in a way that would use the commit message as github release description. Unfortunately, we have to to it manually because of #1748 I would love to hear better strategies to maintain a transparent changelog!

**Review by Mogge — APPROVED** [review]
@mattwr18 when you merge this, can you please update the github release (created by our build server) with the **diff** of this PR, please?

**Pull request closed without merging**
