### PR TITLE
🍰 Added Language Tag For Posts

### LINKED ISSUE #2239: 🚀 [Feature] Show Language On Post Page
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2019-11-14T07:44:03Z" title="Thursday, November 14th 2019, 8:44:03 am +01:00">Nov 14, 2019</time>_
_Closed <time datetime="2019-12-30T14:38:59Z" title="Monday, December 30th 2019, 3:38:59 pm +01:00">Dec 30, 2019</time>_
---

## :rocket: Feature

If you go directly on the posts page the language of the post should be seen there.

### User Problem

If no users can see the language the author has set for their post nobody is able to make the author aware to maybe correct this.

This makes informations in our network less reliable and is an additional reason for bad user experience.
If a user selects English language in the filter of the main page they will see mostly German posts with the wrong post language setting.
A very bad experience for english nativ speakers!

### Implementation

See create post page.

### Design & Layout

Just show the language of the post on its page here:

Bildschirmfoto 2019-11-14 um 08 33 44

Position like on the create post page:

Bildschirmfoto 2019-11-14 um 08 33 19

### Validation

- none

### Additional context

- none

### PR DESCRIPTION
**Pull request by Tirokk**
> [Mozar10](https://github.com/Mozar10) **Authored by [Mozar10](https://github.com/Mozar10)**
_<time datetime="2019-12-27T20:07:53Z" title="Friday, December 27th 2019, 9:07:53 pm +01:00">Dec 27, 2019</time>_
_Merged <time datetime="2019-12-30T14:38:59Z" title="Monday, December 30th 2019, 3:38:59 pm +01:00">Dec 30, 2019</time>_
---

## 🍰 Pullrequest

Added a `ds-tag` which displays `post.language` , `v-if` the post has a language. Added style to float right.

On local:

2239-fix

### Issues
- fixes #2239 

### Todo
- [X] None

### CODE REVIEW

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2019-12-27T20:33:31Z" title="Friday, December 27th 2019, 9:33:31 pm +01:00">Dec 27, 2019</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/3382/specs"></a> <b title="Passed">50</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/3382/failures"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | 7b5916c76f |
| **Started** | Dec 29, 2019 7:51 PM |
| **Ended** | Dec 29, 2019 8:03 PM |
| **Duration** | 11:21 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Chromium 79  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/3382/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings)

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-12-30T14:38:53Z" title="Monday, December 30th 2019, 3:38:53 pm +01:00">Dec 30, 2019</time>_

---


Nice! :+1: @Mozar10 thank you so much!

For your next PR I suggest that you try out [`vue-test-utils`](https://vue-test-utils.vuejs.org/). You can make your PRs even better by adding frontend tests. You can find a lot of people who are familiar with frontend testing in our open-source community.

**Comment by Tirokk** [comment]
> [Mozar10](https://github.com/Mozar10) **Authored by [Mozar10](https://github.com/Mozar10)**
_<time datetime="2020-01-01T08:37:42Z" title="Wednesday, January 1st 2020, 9:37:42 am +01:00">Jan 1, 2020</time>_

---


@roschaefer Sure will include some tests in my next PR :+1:

**Review by Mogge — APPROVED** [review]
Nice done @Mozar10 !!! 🚀🌟

Congratulations! 
Wonderful that you contributed to the project. 🤗

There's a minor lint error.
If the build passes after you fix it, we can merge …

**Pull request closed without merging**
