### PR TITLE
feat: swap user name<=>handle for discriminability

### LINKED ISSUE #2384: 🚀 [Feature] Swap user unique slug and name
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-11-30T09:58:58Z" title="Saturday, November 30th 2019, 10:58:58 am +01:00">Nov 30, 2019</time>_
_Closed <time datetime="2019-12-03T17:46:34Z" title="Tuesday, December 3rd 2019, 6:46:34 pm +01:00">Dec 3, 2019</time>_
---

## :rocket: Feature

How about giving the unique user name (aka handle, aka slug) a more noticeable appearance? We could do that by putting the handle on the first line above the user name.

### User Problem

We had a couple of posts where people went crazy because of "hijacked" profiles. Those hijacked profiles was really just a profile with the same data as some other profile, including avatar and name.

### Design & Layout

Screenshot - 2019-11-30T110933 044

### Validation

Well, it's hard to really fix this problem. But maybe it's a step towards the solution.

### Additional context

The posts in our network for reference: 
https://human-connection.social/post/9cd34c9a-034f-4766-892c-3243ba76dc2f/wer-bist-du-1#commentId-ae95880d-84ac-47e3-bf1e-7ca2741d99c3
https://human-connection.social/post/e08c267b-1f02-4e8a-a78f-939d8f9843e3/mein-profil-gehort-mir#commentId-4f80126b-2418-4bc3-b6dd-2ea909e0ac9f

### PR DESCRIPTION
**Pull request by Tirokk**
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-11-30T10:05:12Z" title="Saturday, November 30th 2019, 11:05:12 am +01:00">Nov 30, 2019</time>_
_Merged <time datetime="2019-12-03T17:46:34Z" title="Tuesday, December 3rd 2019, 6:46:34 pm +01:00">Dec 3, 2019</time>_
---

## 🍰 Pullrequest
Before:
Screenshot - 2019-11-30T110501 902

After:
Screenshot - 2019-11-30T110439 931

### Issues

- fix #2384

### CODE REVIEW

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2019-11-30T10:37:14Z" title="Saturday, November 30th 2019, 11:37:14 am +01:00">Nov 30, 2019</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/2563/specs"></a> <b title="Passed">48</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/2563/failures"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | cf120f2c5f |
| **Started** | Dec 3, 2019 12:10 AM |
| **Ended** | Dec 3, 2019 12:23 AM |
| **Duration** | 12:55 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Chromium 78  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/2563/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings)

**Comment by Tirokk** [comment]
> [alina-beck](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2019-12-02T07:50:24Z" title="Monday, December 2nd 2019, 8:50:24 am +01:00">Dec 2, 2019</time>_

---


Not exactly part of the issue but I would love it if we could put the `name` next to the `slug` and the `date` below the two! Think we could do that in this PR?

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-12-02T23:56:08Z" title="Tuesday, December 3rd 2019, 12:56:08 am +01:00">Dec 3, 2019</time>_

---


@alina-beck 

Screenshot - 2019-12-03T005444 807

?

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-12-03T17:30:54Z" title="Tuesday, December 3rd 2019, 6:30:54 pm +01:00">Dec 3, 2019</time>_

---


great @alina-beck , @roschaefer I was gonna ask for the same thing! 
I think the clock is a little too high for my liking, but certainly this is an improvement... I'll have a better look at the code as soon as I have time

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-12-03T17:46:23Z" title="Tuesday, December 3rd 2019, 6:46:23 pm +01:00">Dec 3, 2019</time>_

---


Well then, two approvals, merge I would say?

**Comment by Tirokk** [comment]
> [alina-beck](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2019-12-04T07:26:58Z" title="Wednesday, December 4th 2019, 8:26:58 am +01:00">Dec 4, 2019</time>_

---


I'll fix the icon position globally – I've seen something similar in other places before. Great work @roschaefer! 😁

**Review by Mogge — APPROVED** [review]
good thing

**Pull request closed without merging**
