### PR TITLE
Disable the location.reloads

### PR DESCRIPTION
**Pull request by Tirokk**
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-06-06T10:37:50Z" title="Thursday, June 6th 2019, 12:37:50 pm +02:00">Jun 6, 2019</time>_
_Merged <time datetime="2019-06-06T17:17:50Z" title="Thursday, June 6th 2019, 7:17:50 pm +02:00">Jun 6, 2019</time>_
---

It might create better user experience, but for the small user group I
think the complexity is worse than the feature itself.

### Issues

- None

### Todo

- [X] None

### CODE REVIEW

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-06-06T10:51:49Z" title="Thursday, June 6th 2019, 12:51:49 pm +02:00">Jun 6, 2019</time>_

---


I could have done this @roschaefer hehehe
beat me to it :stuck_out_tongue_closed_eyes:

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-06-06T16:53:30Z" title="Thursday, June 6th 2019, 6:53:30 pm +02:00">Jun 6, 2019</time>_

---


@mattwr18 nice! Thank you for the tests!

thank you

**Comment by Tirokk** [comment]
> [codecov[bot]](https://github.com/apps/codecov) **Authored by [codecov[bot]](https://github.com/apps/codecov)**
_<time datetime="2019-06-06T17:15:39Z" title="Thursday, June 6th 2019, 7:15:39 pm +02:00">Jun 6, 2019</time>_

---


# [Codecov](https://codecov.io/gh/Human-Connection/Human-Connection/pull/761?src=pr&el=h1) Report
> Merging [#761](https://codecov.io/gh/Human-Connection/Human-Connection/pull/761?src=pr&el=desc) into [master](https://codecov.io/gh/Human-Connection/Human-Connection/commit/ab719eca3e1cab4de34a626720b45fe9841d63e8?src=pr&el=desc) will **decrease** coverage by `0.04%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/Human-Connection/Human-Connection/pull/761?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #761      +/-   ##
==========================================
- Coverage    24.1%   24.06%   -0.04%     
==========================================
  Files         168      168              
  Lines        2336     2332       -4     
  Branches      118      118              
==========================================
- Hits          563      561       -2     
+ Misses       1741     1739       -2     
  Partials       32       32
```


| [Impacted Files](https://codecov.io/gh/Human-Connection/Human-Connection/pull/761?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [webapp/components/Modal/DisableModal.vue](https://codecov.io/gh/Human-Connection/Human-Connection/pull/761/diff?src=pr&el=tree#diff-d2ViYXBwL2NvbXBvbmVudHMvTW9kYWwvRGlzYWJsZU1vZGFsLnZ1ZQ==) | `89.47% <ø> (+3.76%)` | :arrow_up: |
| [webapp/components/ReleaseModal/ReleaseModal.vue](https://codecov.io/gh/Human-Connection/Human-Connection/pull/761/diff?src=pr&el=tree#diff-d2ViYXBwL2NvbXBvbmVudHMvUmVsZWFzZU1vZGFsL1JlbGVhc2VNb2RhbC52dWU=) | `100% <ø> (+5.88%)` | :arrow_up: |

**Review by Mogge — APPROVED** [review]
Thanks for getting to this @roschaefer 
:smile_cat:

**Pull request closed without merging**
