### PR TITLE
[TEST] Save user setting to show embed code

### PR DESCRIPTION
**Pull request by Tirokk**
> [ogerly](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-09-23T18:20:35Z" title="Monday, September 23rd 2019, 8:20:35 pm +02:00">Sep 23, 2019</time>_
_Merged <time datetime="2019-10-10T12:58:52Z" title="Thursday, October 10th 2019, 2:58:52 pm +02:00">Oct 10, 2019</time>_
---

continue here #1852

### CODE REVIEW

**Comment by Tirokk** [comment]
> [datenbrei](https://github.com/datenbrei) **Authored by [datenbrei](https://github.com/datenbrei)**
_<time datetime="2019-09-24T12:57:49Z" title="Tuesday, September 24th 2019, 2:57:49 pm +02:00">Sep 24, 2019</time>_

---


Looks good. But as discussed, merge this in just, if at also has an influence on the embeds. The embeds should initially just ether show up as a pure link or as some kind of box with a hint, that this switch could be set.

**Comment by Tirokk** [comment]
> [ogerly](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-09-25T17:10:13Z" title="Wednesday, September 25th 2019, 7:10:13 pm +02:00">Sep 25, 2019</time>_

---


zu https://github.com/Human-Connection/Human-Connection/pull/1686/commits/e8f771b59aca0ff25df41f0867ec9b4d443c8473 
https://youtu.be/SFKWenwSAvM

**Comment by Tirokk** [comment]
> [alina-beck](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2019-10-02T22:21:31Z" title="Thursday, October 3rd 2019, 12:21:31 am +02:00">Oct 3, 2019</time>_

---


@ogerly I found the `setNodeMarkup` transformation [in the prosemirror docs](https://prosemirror.net/docs/ref/#transform.Transform.setNodeMarkup) – not sure this is what we need but it sounds like it could help us turn the `Embed` into a `Link` node... maybe? 🙂

**Comment by Tirokk** [comment]
> [ogerly](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-10-09T06:57:37Z" title="Wednesday, October 9th 2019, 8:57:37 am +02:00">Oct 9, 2019</time>_

---


nice @mattwr18 thanks !!!!

**Comment by Tirokk** [comment]
> [ogerly](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-10-09T13:42:33Z" title="Wednesday, October 9th 2019, 3:42:33 pm +02:00">Oct 9, 2019</time>_

---


ok
 
giphy

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-10-09T13:44:39Z" title="Wednesday, October 9th 2019, 3:44:39 pm +02:00">Oct 9, 2019</time>_

---


I would say that the storybook for the different scenarios maybe can wait, no @roschaefer??
After all, when you introduced the `Embeds`, you didn't add the stories.
We have flagged this as an issue with data privacy that maybe should have been in before we released `Nitro`, so I would love to see it get deployed to production.
What do you, and others, think?

**Comment by Tirokk** [comment]
> [ogerly](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-10-09T17:42:08Z" title="Wednesday, October 9th 2019, 7:42:08 pm +02:00">Oct 9, 2019</time>_

---


continue here  https://github.com/Human-Connection/Human-Connection/pull/1852

**Review by Mogge — CHANGES_REQUESTED** [review]
I really like the design of the embed. It's exactly how I imagined it. Also the warning what happens when I click on it. It's done really well, almost too good, I feel quite in danger when I confirm the button to allow embeds.

What I would like to see is a storybook for the different scenarios of the embed. Also the code settings page can be improved:
* Show the list of providers by default, even if you don't allow them
* Don't use a red/green button - allowing and not allowing embeds is both fine
* Improve the naming for the translations on the settings page


well done

**Pull request closed without merging**
