### PR TITLE
build: Add semantic PR config

### LINKED ISSUE #3883: 💬 [Question] Semantic PRs Shouldn’t Fail If There’s Only One Commit
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2020-09-17T10:54:40Z" title="Thursday, September 17th 2020, 12:54:40 pm +02:00">Sep 17, 2020</time>_
_Closed <time datetime="2020-09-18T09:23:02Z" title="Friday, September 18th 2020, 11:23:02 am +02:00">Sep 18, 2020</time>_
---

## :speech_balloon: Question

The semantic pull request doesn’t work if there is only one commit in the PR. That sometimes happen and then the semantic-PR mechanism fail.
I can and will not do a senseless second commit in a PR …

### PR DESCRIPTION
**Pull request by Tirokk**
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2020-09-17T11:03:33Z" title="Thursday, September 17th 2020, 1:03:33 pm +02:00">Sep 17, 2020</time>_
_Merged <time datetime="2020-09-18T09:23:01Z" title="Friday, September 18th 2020, 11:23:01 am +02:00">Sep 18, 2020</time>_
---

- Added 'semantic.yml'.

## 🍰 Pullrequest

The semantic pull request doesn’t work if there is only one commit in the PR. That sometimes happen and then the semantic-PR mechanism fail.
I can and will not do a senseless second commit in a PR …

Description how to change this is here:
https://github.com/zeke/semantic-pull-requests#configuration

### Issues

- fixes #3883

### Todo

- [X] None

### CODE REVIEW

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-09-17T11:46:16Z" title="Thursday, September 17th 2020, 1:46:16 pm +02:00">Sep 17, 2020</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7951/specs?utm_source=github"></a> <b title="Passed">66</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7951/test-results?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | e60bd311a4 |
| **Started** | Sep 17, 2020 11:21 AM |
| **Ended** | Sep 17, 2020 11:46 AM |
| **Duration** | 24:19 <a href="https://on.cypress.io/parallelization?utm_source=github" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Firefox 68  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/7951/specs?utm_source=github)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings?utm_source=github)

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-09-17T12:29:21Z" title="Thursday, September 17th 2020, 2:29:21 pm +02:00">Sep 17, 2020</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7953/specs?utm_source=github"></a> <b title="Passed">66</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7953/test-results?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | e1c5329427 <span style="cursor:help;" title="Your CI provider generated this commit by merging this branch into the target branch.">ℹ️</span> |
| **Started** | Sep 17, 2020 12:07 PM |
| **Ended** | Sep 17, 2020 12:29 PM |
| **Duration** | 21:43 <a href="https://on.cypress.io/parallelization?utm_source=github" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Firefox 68  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/7953/specs?utm_source=github)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings?utm_source=github)

**Comment by Tirokk** [comment]
> [ogerly](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2020-09-18T09:28:41Z" title="Friday, September 18th 2020, 11:28:41 am +02:00">Sep 18, 2020</time>_

---


ok

**Review by Mogge — APPROVED** [review]
Great. Thank you

**Pull request closed without merging**
