### PR TITLE
206 setup neo4j db with dump

### LINKED ISSUE #206: Neo4J DB initialization
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-02-07T10:52:23Z" title="Thursday, February 7th 2019, 11:52:23 am +01:00">Feb 7, 2019</time>_
_Closed <time datetime="2019-06-05T12:11:32Z" title="Wednesday, June 5th 2019, 2:11:32 pm +02:00">Jun 5, 2019</time>_
---

**Is your feature request related to a problem? Please describe.**
For performance, we would like to have a reproducible set of indices in our Neo4J database.

**Describe the solution you'd like**
Write a script, e.g. `migrate` or `db:setup` to create indices in Neo4J. This script will be run when a container starts and it should run after the default `entrypoint.sh`.

**Additional context**:
[Read about how to create an index in Neo4J](https://www.quackit.com/neo4j/tutorial/neo4j_create_an_index_using_cypher.cfm)

We could also add an initial user with admin privileges. This could replace the need for an unauthenticated server for seeding during our test suite.

### PR DESCRIPTION
**Pull request by Tirokk**
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-05-31T19:06:40Z" title="Friday, May 31st 2019, 9:06:40 pm +02:00">May 31, 2019</time>_
_Closed <time datetime="2019-06-04T22:32:56Z" title="Wednesday, June 5th 2019, 12:32:56 am +02:00">Jun 5, 2019</time>_
---

## 🍰 Pullrequest
Yet another reason to use docker: You don't have to worry about the unique constraints anymore.

### Issues

- fixes #206 

### Todo

- [X] None

### CODE REVIEW

**Comment by Tirokk** [comment]
> [codecov[bot]](https://github.com/apps/codecov) **Authored by [codecov[bot]](https://github.com/apps/codecov)**
_<time datetime="2019-05-31T19:44:53Z" title="Friday, May 31st 2019, 9:44:53 pm +02:00">May 31, 2019</time>_

---


# [Codecov](https://codecov.io/gh/Human-Connection/Human-Connection/pull/715?src=pr&el=h1) Report
> Merging [#715](https://codecov.io/gh/Human-Connection/Human-Connection/pull/715?src=pr&el=desc) into [master](https://codecov.io/gh/Human-Connection/Human-Connection/commit/13a2f771f86ca96b3fb55de1bd949782edfc608a?src=pr&el=desc) will **not change** coverage.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/Human-Connection/Human-Connection/pull/715?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##           master     #715   +/-   ##
=======================================
  Coverage   21.15%   21.15%           
=======================================
  Files         162      162           
  Lines        2274     2274           
  Branches      113      113           
=======================================
  Hits          481      481           
  Misses       1765     1765           
  Partials       28       28
```

**Comment by Tirokk** [comment]
> [codecov[bot]](https://github.com/apps/codecov) **Authored by [codecov[bot]](https://github.com/apps/codecov)**
_<time datetime="2019-05-31T19:44:53Z" title="Friday, May 31st 2019, 9:44:53 pm +02:00">May 31, 2019</time>_

---


# [Codecov](https://codecov.io/gh/Human-Connection/Human-Connection/pull/715?src=pr&el=h1) Report
> Merging [#715](https://codecov.io/gh/Human-Connection/Human-Connection/pull/715?src=pr&el=desc) into [master](https://codecov.io/gh/Human-Connection/Human-Connection/commit/13a2f771f86ca96b3fb55de1bd949782edfc608a?src=pr&el=desc) will **not change** coverage.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/Human-Connection/Human-Connection/pull/715?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##           master     #715   +/-   ##
=======================================
  Coverage   21.15%   21.15%           
=======================================
  Files         162      162           
  Lines        2274     2274           
  Branches      113      113           
=======================================
  Hits          481      481           
  Misses       1765     1765           
  Partials       28       28
```

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-05-31T21:53:45Z" title="Friday, May 31st 2019, 11:53:45 pm +02:00">May 31, 2019</time>_

---


This is odd. The constraints won't get imported. I tried to dump my host machine database instance. The neo4j constraints get imported when importing back to my host machine, but they do not get imported when importing it in the container.

Our build server fails because of missing constraints.

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-06-04T22:32:56Z" title="Wednesday, June 5th 2019, 12:32:56 am +02:00">Jun 5, 2019</time>_

---


closed in favour of #739

**Review by Mogge — APPROVED** [review]

**Pull request closed without merging**
