### PR TITLE
Fix? flaky cypress by waiting for <no-ssr> content

### PR DESCRIPTION
**Pull request by Tirokk**
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-04-18T17:06:06Z" title="Thursday, April 18th 2019, 7:06:06 pm +02:00">Apr 18, 2019</time>_
_Merged <time datetime="2019-04-29T17:50:48Z" title="Monday, April 29th 2019, 7:50:48 pm +02:00">Apr 29, 2019</time>_
---

Content menu is a client-side rendered component. Maybe an extra
assertion will wait for it? That's how you can flix flaky cucumbers if
you use capybara.

### Issues

- [X] None

### Checklist

- [X] None

### How2Test

- [X] None

### Todo

- [X] None

### CODE REVIEW

**Comment by Tirokk** [comment]
> [ulfgebhardt](https://github.com/ulfgebhardt) **Authored by [ulfgebhardt](https://github.com/ulfgebhardt)**
_<time datetime="2019-04-19T07:07:49Z" title="Friday, April 19th 2019, 9:07:49 am +02:00">Apr 19, 2019</time>_

---


image

I approved this - it is for this test? You do not mention which flanky test you are fixing - from the change it seems to be an menu button -> is it the report user test?

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-04-19T11:13:51Z" title="Friday, April 19th 2019, 1:13:51 pm +02:00">Apr 19, 2019</time>_

---


Yes, it's the `ReportUser.feature` test. Unfortunately, that does not help as you can see. The build server is still failing for that reason.

If my assumption is correct, it might fail because of the `<no-ssr>` around the content menu. Another try would be to check why it's not rendered on the server and to check what is so different for the content menu component on the other pages? I mean, it's always failing for the user, but it does not fail on the post page or the comment page. Could you have a look @ulfgebhardt ?

**Comment by Tirokk** [comment]
> [ulfgebhardt](https://github.com/ulfgebhardt) **Authored by [ulfgebhardt](https://github.com/ulfgebhardt)**
_<time datetime="2019-04-22T10:42:28Z" title="Monday, April 22nd 2019, 12:42:28 pm +02:00">Apr 22, 2019</time>_

---


I think it is because `ds-button-ghost`. This class seems to be added on runtime, since its not in the code.
image

if i am correct the button will show a bit later on the UI when the rest is loaded. I am not sure tho. This would explain `ds-button-ghost`.
Another possibility is that you want to press the button hidden behind the `dot-menu` - which is not visible till you press the dots. From Travis i cannot tell which button you are trying to click.

If you want the normal user way:
- navigate to correct page
- trigger `dot-menu`
- wait till all entries appeared
- click report
- continue with test...

Or just `force` the click?

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-04-23T15:38:25Z" title="Tuesday, April 23rd 2019, 5:38:25 pm +02:00">Apr 23, 2019</time>_

---


@ulfgebhardt great research! :+1: Using `{ force: true }` unfortunately does not help, I tried that earlier.

Could you see what happens if you remove `<no-ssr>`? Sometimes it's used without any reason.

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-04-27T21:24:36Z" title="Saturday, April 27th 2019, 11:24:36 pm +02:00">Apr 27, 2019</time>_

---


@roschaefer @ulfgebhardt, I think I fixed this flaky test by adding a class to the `content-menu`... it would be nice to get it working without, but if this can save us from needing to consistently rerun our builds, I feel like it's a smal price to pay.
I needed to rerun the build three or four times just today to get my feature all green :open_mouth: 
Not sure if this will work every time, but it passed both builds on the first try on this branch

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-04-29T17:50:24Z" title="Monday, April 29th 2019, 7:50:24 pm +02:00">Apr 29, 2019</time>_

---


@mattwr18 adding one more css class is no problem at all. If that solves all our problems, I would be interested in *why* the class fixes the flaky test.. :thinking:  Do you have an explanation?

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-04-29T18:01:42Z" title="Monday, April 29th 2019, 8:01:42 pm +02:00">Apr 29, 2019</time>_

---


no, I don't have an explanation as of yet, I kinda stumbled into this, and I'm not sure if it actually solves the issue... I'm hesitant to declare it a win yet.... As the build for the CreateComment has failed again cause of this, I have pulled in the latest changes and will see if it passes the first try.

I got to this by adding a bunch of `get` and `contains` that would wait till the post info had been brought in after reading cypress issues to do with the page refreshing while the cypress test was trying to execute the failing step. This caused the issue that there were two `.content-menu-trigger` classes, one for the user, one for the post. When I added the class it started reliably passing locally, which is when I started removing code to see if it would still pass without the extra `get` `contains`.

**Review by Mogge — APPROVED** [review]

**Review by Mogge — APPROVED** [review]
Let's try adding it to the master

**Pull request closed without merging**
