### PR TITLE
Fix placeholder text not translating bug

### LINKED ISSUE #583: 🐛 Placeholder in CommentForm does not change Localisation dynamically
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2019-05-09T08:51:00Z" title="Thursday, May 9th 2019, 10:51:00 am +02:00">May 9, 2019</time>_
_Closed <time datetime="2019-05-29T06:08:30Z" title="Wednesday, May 29th 2019, 8:08:30 am +02:00">May 29, 2019</time>_
---

## :bug: Bugreport

If you change the language the `placeholder` in CommentForm does not change localisation.

### Steps to reproduce the behavior
1. If you go to the profile of a user …
2. … and click on a post …
3. … and on this post scroll down to the bottom to the CommentForm
4. change language
5. you can see that the `placeholder` text in the CommentForm edit field does not change localisation

### Expected behavior

There should be an edit field displayed in the CommentForm.
The CommentForm edit field `placeholder` text should change the localisation.

### Version & Environment
 Type: Desktop      
 - OS: macOS      
 - Browser: FireFox 

### Additional Context
This problem is related to the use of `tiptap` editor.

### PR DESCRIPTION
**Pull request by Tirokk**
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-05-28T15:53:18Z" title="Tuesday, May 28th 2019, 5:53:18 pm +02:00">May 28, 2019</time>_
_Merged <time datetime="2019-05-29T06:08:30Z" title="Wednesday, May 29th 2019, 8:08:30 am +02:00">May 29, 2019</time>_
---

- tiptap-extensions are not reactive
- we must call a method to change them dynamically
- emit changeLanguage event, which is listened for by the Editor component, which then calls a method to set the emptyNodeText of tiptap

### Issues

- fixes #583

### CODE REVIEW

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-05-28T16:40:46Z" title="Tuesday, May 28th 2019, 6:40:46 pm +02:00">May 28, 2019</time>_

---


@roschaefer, maybe?? we could not have placeholder text for example??
or there might be another way
One of the maintainers just responded to my approach on the issue I shared, saying |

https://github.com/scrumpy/tiptap/issues/17
```
@mattwr18 That should be fine. Would have done that in a similar way.

I should mention that this won't work in IE 11 without polyfill for Proxys
```

**Comment by Tirokk** [comment]
> [codecov[bot]](https://github.com/apps/codecov) **Authored by [codecov[bot]](https://github.com/apps/codecov)**
_<time datetime="2019-05-29T06:44:39Z" title="Wednesday, May 29th 2019, 8:44:39 am +02:00">May 29, 2019</time>_

---


# [Codecov](https://codecov.io/gh/Human-Connection/Human-Connection/pull/695?src=pr&el=h1) Report
> Merging [#695](https://codecov.io/gh/Human-Connection/Human-Connection/pull/695?src=pr&el=desc) into [master](https://codecov.io/gh/Human-Connection/Human-Connection/commit/9c53e135c8514201b438ba3ed4de197b69249d0a?src=pr&el=desc) will **increase** coverage by `0.15%`.
> The diff coverage is `25%`.

[Impacted file tree graph](https://codecov.io/gh/Human-Connection/Human-Connection/pull/695?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #695      +/-   ##
==========================================
+ Coverage   21.27%   21.42%   +0.15%     
==========================================
  Files         161      161              
  Lines        2257     2288      +31     
  Branches      113      124      +11     
==========================================
+ Hits          480      490      +10     
- Misses       1749     1770      +21     
  Partials       28       28
```


| [Impacted Files](https://codecov.io/gh/Human-Connection/Human-Connection/pull/695?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [webapp/components/LocaleSwitch.vue](https://codecov.io/gh/Human-Connection/Human-Connection/pull/695/diff?src=pr&el=tree#diff-d2ViYXBwL2NvbXBvbmVudHMvTG9jYWxlU3dpdGNoLnZ1ZQ==) | `0% <0%> (ø)` | :arrow_up: |
| [webapp/components/Editor/index.vue](https://codecov.io/gh/Human-Connection/Human-Connection/pull/695/diff?src=pr&el=tree#diff-d2ViYXBwL2NvbXBvbmVudHMvRWRpdG9yL2luZGV4LnZ1ZQ==) | `22.45% <33.33%> (+0.34%)` | :arrow_up: |
| [webapp/layouts/default.vue](https://codecov.io/gh/Human-Connection/Human-Connection/pull/695/diff?src=pr&el=tree#diff-d2ViYXBwL2xheW91dHMvZGVmYXVsdC52dWU=) | `0% <0%> (ø)` | :arrow_up: |
| [webapp/components/User/index.vue](https://codecov.io/gh/Human-Connection/Human-Connection/pull/695/diff?src=pr&el=tree#diff-d2ViYXBwL2NvbXBvbmVudHMvVXNlci9pbmRleC52dWU=) | `95.24% <0%> (+2.38%)` | :arrow_up: |
| [webapp/pages/profile/\_id/\_slug.vue](https://codecov.io/gh/Human-Connection/Human-Connection/pull/695/diff?src=pr&el=tree#diff-d2ViYXBwL3BhZ2VzL3Byb2ZpbGUvX2lkL19zbHVnLnZ1ZQ==) | `3.23% <0%> (+3.23%)` | :arrow_up: |

**Review by Mogge — APPROVED** [review]
Ewww, this is one of the rare occasions where I neither want to "Approve" or do know how to "Request changes". If there is no better way to achive this, it's OK for me. Isn't there a better way @mattwr18 ?

dirty

**Review by Mogge — APPROVED** [review]
Could have been more dirty at the end. @mattwr18 @roschaefer 
I approve and would say, just merge it.

**Pull request closed without merging**
