### PR TITLE
feat: 🍰 Set up Vue-Apollo Subscriptions

### LINKED ISSUE #1703: 🚀 [Feature] Add Vue-Apollo Subscriptions
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-09-24T10:22:07Z" title="Tuesday, September 24th 2019, 12:22:07 pm +02:00">Sep 24, 2019</time>_
_Closed <time datetime="2020-02-12T17:02:06Z" title="Wednesday, February 12th 2020, 6:02:06 pm +01:00">Feb 12, 2020</time>_
---

## :rocket: Feature

We should set up `Subscriptions` for our site.
https://vue-apollo.netlify.com/guide/apollo/subscriptions.html#setup
With `Subscriptions`, we can update our `NewsFeed`, `NotificationsMenu`, etc... when there are changes

### PR DESCRIPTION
**Pull request by Tirokk**
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-09-24T11:11:40Z" title="Tuesday, September 24th 2019, 1:11:40 pm +02:00">Sep 24, 2019</time>_
_Merged <time datetime="2020-02-12T17:02:06Z" title="Wednesday, February 12th 2020, 6:02:06 pm +01:00">Feb 12, 2020</time>_
---

### Issues

- fixes #1703 

### Todo

- [x] Test that server-side works
- [x] Set it up from the client side
- [x] Subscribe to `notifications` query
- [ ] Set it up as `wss` for safety

### CODE REVIEW

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-10-21T14:31:36Z" title="Monday, October 21st 2019, 4:31:36 pm +02:00">Oct 21, 2019</time>_

---


@roschaefer do you want to have a look at this, maybe together, or should we just close this?

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2019-11-25T14:50:27Z" title="Monday, November 25th 2019, 3:50:27 pm +01:00">Nov 25, 2019</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/5092/specs"></a> <b title="Passed">61</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/5092/failures"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | 3108f86f5e |
| **Started** | Feb 12, 2020 3:39 PM |
| **Ended** | Feb 12, 2020 3:54 PM |
| **Duration** | 14:44 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Electron 78  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/5092/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings)

**Comment by Tirokk** [comment]
> [stale[bot]](https://github.com/apps/stale) **Authored by [stale[bot]](https://github.com/apps/stale)**
_<time datetime="2020-01-24T15:43:19Z" title="Friday, January 24th 2020, 4:43:19 pm +01:00">Jan 24, 2020</time>_

---


This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2020-02-05T19:55:08Z" title="Wednesday, February 5th 2020, 8:55:08 pm +01:00">Feb 5, 2020</time>_

---


this is ready for a `WIP` PR review @Human-Connection/hc-dev-team ...
maybe it is mergeable, but I noticed this comment on the `graphql-subscriptions` github page
https://github.com/apollographql/graphql-subscriptions
```
Note that the default PubSub implementation is intended for demo purposes. It only works if you have a single instance of your server and doesn't scale beyond a couple of connections. For production usage you'll want to use one of the PubSub implementations backed by an external store. (e.g. Redis)
```

It certainly seems to say that we shouldn't use this for production. Should we set it up with `Redis` then? what do you think @roschaefer ??

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2020-02-12T15:10:06Z" title="Wednesday, February 12th 2020, 4:10:06 pm +01:00">Feb 12, 2020</time>_

---


Not nothing will happen, it will fallback to using the `PubSub` "for demo purposes" implementation.
Yes, it would need to be deployed with the `redis` helm chart.
I need to rebase this, and question I have is whether we want to commit fully to `Helm` and introduce the `redis` helm chart at the same time.
For me, this is not necessary because we are not maintaining the `helm` chart, so it is the same as using a `helm` chart for `cert-manager` or `grafana`, which is separate from our `human-connection` helm chart. 
What do you think?

**Review by Mogge — APPROVED** [review]
subscribe

Nice, I had a look into the changes since my last visit. It looks easy enough! If you don't have a redis server running (e.g. in `development`) then nothing happens, right?

For me this looks ready to merge - if we can deploy it along with the redis helm chart.

**Pull request closed without merging**
