### PR TITLE
Avatar should be centered on profile page

### PR DESCRIPTION
**Pull request by Tirokk**
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-09-06T23:40:57Z" title="Saturday, September 7th 2019, 1:40:57 am +02:00">Sep 7, 2019</time>_
_Merged <time datetime="2019-09-09T17:16:57Z" title="Monday, September 9th 2019, 7:16:57 pm +02:00">Sep 9, 2019</time>_
---

This is a fix of e04eedf0d07ff66dba3e881e9ef8bdf5a868619e

### Issues

- None

### Todo

- [X] None

### CODE REVIEW

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-09-09T13:02:44Z" title="Monday, September 9th 2019, 3:02:44 pm +02:00">Sep 9, 2019</time>_

---


@mattwr18 thank you for the tip with `scoped` so much easier! No unwanted side-effects!

**Before**
Screenshot - 2019-09-09T145802 611

**After**
Screenshot - 2019-09-09T150338 077

**Comment by Tirokk** [comment]
> [alina-beck](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2019-09-09T13:50:58Z" title="Monday, September 9th 2019, 3:50:58 pm +02:00">Sep 9, 2019</time>_

---


build is failing because of a lint error I think... you know what would be awesome? a pre-commit hook running `eslint`! :smile:

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-09-09T14:04:32Z" title="Monday, September 9th 2019, 4:04:32 pm +02:00">Sep 9, 2019</time>_

---


we actually discussed that @alina-beck... it's sooo annoying!!!

**Review by Mogge — APPROVED** [review]
great! I still don't know which context you were getting this weird CSS, but if this fixes it, I'm all for it

**Review by Mogge — APPROVED** [review]
Just the lint …
I corrected … 🤗

Super to have that in place again @roschaefer !!! 💫

Someone can merge, if the build is passing …

in Place

**Pull request closed without merging**
