### PR TITLE
Hide shout count on user profile unless my profile

### LINKED ISSUE #1995: 🚀 [Feature] Shouts should be hidden from other users
> [alina-beck](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2019-10-22T11:05:37Z" title="Tuesday, October 22nd 2019, 1:05:37 pm +02:00">Oct 22, 2019</time>_
_Closed <time datetime="2019-10-24T06:41:33Z" title="Thursday, October 24th 2019, 8:41:33 am +02:00">Oct 24, 2019</time>_
---

## :rocket: Feature
brought up by Dennis

In the future users should be able to decide if they want their comments and shouts to be public or private (see #1747). Until then all shouts should be hidden from other users and only be visible on one's own profile page.

### PR DESCRIPTION
**Pull request by Tirokk**
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-10-23T12:11:49Z" title="Wednesday, October 23rd 2019, 2:11:49 pm +02:00">Oct 23, 2019</time>_
_Merged <time datetime="2019-10-24T06:41:33Z" title="Thursday, October 24th 2019, 8:41:33 am +02:00">Oct 24, 2019</time>_
---

- we were asked to hide the shouts from other users by Dennis Hack, he
believes people will be more likely to shout a post if it is anonymous.
This only works from our UI to our backend... further steps would need
to be taken to truly make it anonymous. Also, we were asked to implement
it in such a way as to give the user the choice to show their shouts to
others.

Co-authored-by: Alina Beck <alina.beck@mail.com>

### Issues

- fixes #1995

### CODE REVIEW

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-10-23T12:20:03Z" title="Wednesday, October 23rd 2019, 2:20:03 pm +02:00">Oct 23, 2019</time>_

---


thanks to @alina-beck, we didn't break the styling with this feature

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-10-23T12:30:27Z" title="Wednesday, October 23rd 2019, 2:30:27 pm +02:00">Oct 23, 2019</time>_

---


Screenshot from 2019-10-23 14-01-15
Screenshot from 2019-10-23 14-01-29

**Comment by Tirokk** [comment]
> [datenbrei](https://github.com/datenbrei) **Authored by [datenbrei](https://github.com/datenbrei)**
_<time datetime="2019-10-23T13:08:42Z" title="Wednesday, October 23rd 2019, 3:08:42 pm +02:00">Oct 23, 2019</time>_

---


Looks good to me, though I'm not able to check the code.

**Review by Mogge — APPROVED** [review]
Great for now! THANKS!

**Review by Mogge — APPROVED** [review]
ok

**Pull request closed without merging**
