### PR TITLE
Cursor fixes

### LINKED ISSUE #1438: 🐛 [Bug] Mouse cursor over Logo seems to be non-clickable
> [datenbrei](https://github.com/datenbrei) **Authored by [datenbrei](https://github.com/datenbrei)**
_<time datetime="2019-08-30T08:33:03Z" title="Friday, August 30th 2019, 10:33:03 am +02:00">Aug 30, 2019</time>_
_Closed <time datetime="2019-09-04T21:20:58Z" title="Wednesday, September 4th 2019, 11:20:58 pm +02:00">Sep 4, 2019</time>_
---

## :bug: Bugreport

If the mouse cursor is over the top left logo it does not change to a "hand". This looks like, as if the logo would not be clickable, but it is.

### Steps to reproduce the behavior
1. Move the mouse over the top left logo

### Expected behavior

As on every other clickable part of the page the logo should also be appear as clickable.

### Version & Environment
 Type: [Desktop]      
 - OS: [Linux]      
 - Browser: [Firefox] 
 - Version [68.0.1]  
 - Device: [Notebook]  

### Additional context

Minor bug, not important, just not nice.

### LINKED ISSUE #1465: 🐛 [Bug] Wrong cursor on post
> [alina-beck](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2019-09-04T09:19:52Z" title="Wednesday, September 4th 2019, 11:19:52 am +02:00">Sep 4, 2019</time>_
_Closed <time datetime="2019-09-04T21:20:58Z" title="Wednesday, September 4th 2019, 11:20:58 pm +02:00">Sep 4, 2019</time>_
---

## :bug: Bugreport
reported by @ulfgebhardt 

The cursor is set to `pointer` on the whole post although there is no interaction possible.

### Steps to reproduce the behavior
1. Go to a post page `/post/something`
2. Hover over the post

### Expected behavior
Only interactive elements should have a `cursor: pointer`

### PR DESCRIPTION
**Pull request by Tirokk**
> [alina-beck](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2019-09-04T15:27:46Z" title="Wednesday, September 4th 2019, 5:27:46 pm +02:00">Sep 4, 2019</time>_
_Merged <time datetime="2019-09-04T21:20:58Z" title="Wednesday, September 4th 2019, 11:20:58 pm +02:00">Sep 4, 2019</time>_
---

## 🍰 Pullrequest
- sets cursor to pointer for header logo
- removes pointer from post

### Issues
- fixes #1438 
- fixes #1465

### CODE REVIEW

**Comment by Tirokk** [comment]
> [alina-beck](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2019-09-04T17:44:39Z" title="Wednesday, September 4th 2019, 7:44:39 pm +02:00">Sep 4, 2019</time>_

---


@roschaefer Oh yeah, sorry, I saw this too late! Unfortunately the above command gives me `fatal: invalid reference: 1394-simplify_index_page` – any idea why? I could also just copy the content of the files otherwise...

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-09-04T17:46:21Z" title="Wednesday, September 4th 2019, 7:46:21 pm +02:00">Sep 4, 2019</time>_

---


@alina-beck yes! That's because you don't have the local branch `1394-simplify_index_page`. You could check out the files from the remote branch `origin/1394-simplify_index_page` though.

**Comment by Tirokk** [comment]
> [alina-beck](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2019-09-04T18:03:05Z" title="Wednesday, September 4th 2019, 8:03:05 pm +02:00">Sep 4, 2019</time>_

---


@roschaefer duh. thank you! 😅 how come we don't need the `posts` store anymore, though? is it not being used anywhere else?

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-09-04T18:05:42Z" title="Wednesday, September 4th 2019, 8:05:42 pm +02:00">Sep 4, 2019</time>_

---


the `posts` store was dead code after #1233

**Review by Mogge — CHANGES_REQUESTED** [review]
@alina-beck sorry for being late!

sorry for being late

I fixed this issue in https://github.com/Human-Connection/Human-Connection/pull/1457/files

Unfortunately I couldn't fix the issue #1394 which was the main motivation for the PR.

Could you do:
```
git checkout 1394-simplify_index_page -- webapp/layouts/default.vue webapp/store/posts.js
```
and push that up to this PR?

**Review by Mogge — APPROVED** [review]
Great! :clap:

**Pull request closed without merging**
