### PR TITLE
Update de.json

### LINKED ISSUE #2583: 🐛 [Bug] English Not Fully Translated: 'languageSelectLabel'
> [ogerly](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-12-19T08:01:13Z" title="Thursday, December 19th 2019, 9:01:13 am +01:00">Dec 19, 2019</time>_
_Closed <time datetime="2020-07-08T06:26:16Z" title="Wednesday, July 8th 2020, 8:26:16 am +02:00">Jul 8, 2020</time>_
---

In the english version it is named:
`"languageSelectLabel": "Language of your contribution“`

In german that would be:
"languageSelectLabel": „Sprache deines Beitrags“

I would like to change this, because a lot of people seem to think this is as well the language of the web app and not of the post.

_Originally posted by @Tirokk in https://github.com/Human-Connection/Human-Connection/pull/2351_

### PR DESCRIPTION
**Pull request by Tirokk**
> [erhardtstiefel](https://github.com/erhardtstiefel) **Authored by [erhardtstiefel](https://github.com/erhardtstiefel)**
_<time datetime="2020-01-01T13:34:36Z" title="Wednesday, January 1st 2020, 2:34:36 pm +01:00">Jan 1, 2020</time>_
_Merged <time datetime="2020-01-07T20:45:27Z" title="Tuesday, January 7th 2020, 9:45:27 pm +01:00">Jan 7, 2020</time>_
---

## 🍰 Pullrequest

#2583_de
"Sprache" will be changed to "Sprache deines Beitrags"

### Issues

- This change has to be done also for the other languages. 
I'll try to do so by adding more commits to this PR

### CODE REVIEW

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-01-01T13:59:17Z" title="Wednesday, January 1st 2020, 2:59:17 pm +01:00">Jan 1, 2020</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/3574/specs"></a> <b title="Passed">50</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/3574/failures"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | b744383d92 |
| **Started** | Jan 6, 2020 5:59 PM |
| **Ended** | Jan 6, 2020 6:10 PM |
| **Duration** | 10:47 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Chromium 79  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/3574/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings)

**Comment by Tirokk** [comment]
> [erhardtstiefel](https://github.com/erhardtstiefel) **Authored by [erhardtstiefel](https://github.com/erhardtstiefel)**
_<time datetime="2020-01-01T14:17:07Z" title="Wednesday, January 1st 2020, 3:17:07 pm +01:00">Jan 1, 2020</time>_

---


How can I add more commits to this PR?

**Comment by Tirokk** [comment]
> [Mogge](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2020-01-06T17:39:21Z" title="Monday, January 6th 2020, 6:39:21 pm +01:00">Jan 6, 2020</time>_

---


@erhardtstiefel  just push the new commits in your branch

**Review by Mogge — APPROVED** [review]

**Review by Mogge — APPROVED** [review]
@erhardtstiefel if you want to stop people from merging your code, you can start the title of your PR with `[WIP]` so in this case: `[WIP] Update de.json`.

WIP is an abbreviation for "work-in-progress". Intermediate PRs are great, because they give the development team an opportunity to give early feedback.

**Pull request closed without merging**
