### PR TITLE
Add details to contribution form

### LINKED ISSUE #760: 🚀 [Feature] Author (self) + last active in Create Post
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2019-06-06T07:49:10Z" title="Thursday, June 6th 2019, 9:49:10 am +02:00">Jun 6, 2019</time>_
_Closed <time datetime="2019-08-02T09:13:35Z" title="Friday, August 2nd 2019, 11:13:35 am +02:00">Aug 2, 2019</time>_
---

## :rocket: Feature

Who is the Author? 😎 Who I am. 🖖🏼🤔
And when I was last active?

- show the Avatar and name of the User above the Post title
- show the users last activity date-time underneath the users name

### Design & Layout

Alpha - Create Post - Avatar, Name, Date-Time - Bildschirmfoto 2019-06-06 um 09 12 53

### Additional context

It is already done in the PostCard on the User Profile, Post List. See here:

Nitro - User Profile, Post List, Post Card – Avatar, Name, Date-Time - Bildschirmfoto 2019-06-06 um 09 44 09

### PR DESCRIPTION
**Pull request by Tirokk**
> [aonomike](https://github.com/aonomike) **Authored by [aonomike](https://github.com/aonomike)**
_<time datetime="2019-06-29T17:47:37Z" title="Saturday, June 29th 2019, 7:47:37 pm +02:00">Jun 29, 2019</time>_
_Merged <time datetime="2019-07-29T09:13:50Z" title="Monday, July 29th 2019, 11:13:50 am +02:00">Jul 29, 2019</time>_
---

## 🍰 Pullrequest

Add Author details including last active to the contribution form
### Issues

- None

### Todo

- [X] None

### CODE REVIEW

**Comment by Tirokk** [comment]
> [codecov[bot]](https://github.com/apps/codecov) **Authored by [codecov[bot]](https://github.com/apps/codecov)**
_<time datetime="2019-06-29T17:47:39Z" title="Saturday, June 29th 2019, 7:47:39 pm +02:00">Jun 29, 2019</time>_

---


# [Codecov](https://codecov.io/gh/Human-Connection/Human-Connection/pull/936?src=pr&el=h1) Report
> :exclamation: No coverage uploaded for pull request base (`master@7763083`). [Click here to learn what that means](https://docs.codecov.io/docs/error-reference#section-missing-base-commit).
> The diff coverage is `n/a`.

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-07-12T10:12:38Z" title="Friday, July 12th 2019, 12:12:38 pm +02:00">Jul 12, 2019</time>_

---


We have decided that we definitely decided not to implement the `last active` feature neither in this `PR` nor in the `Relase: Nitro`, so maybe you could remove the `[WIP]` and we can give this a review?
Maybe you could work through the merge conflicts and upload some screen shots?

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-07-29T06:49:17Z" title="Monday, July 29th 2019, 8:49:17 am +02:00">Jul 29, 2019</time>_

---


Screenshot at 2019-07-29 08:44:38

**Review by Mogge — APPROVED** [review]
Hey hey hey @aonomike !
Now our Post creation side looks even more kind of professional and the user is aware, he/she/it is the author and stands with his/her/they name for the content. 🚀👋🏼

We are thankful to have you around with us for so long now.
COOL as ice !!! 

Cool

**Pull request closed without merging**
