### PR TITLE
Filter posts by emotions

### LINKED ISSUE #1488: 🚀 [Feature] Filter by emotions
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-09-05T13:36:48Z" title="Thursday, September 5th 2019, 3:36:48 pm +02:00">Sep 5, 2019</time>_
_Closed <time datetime="2019-09-10T13:53:06Z" title="Tuesday, September 10th 2019, 3:53:06 pm +02:00">Sep 10, 2019</time>_
---

## :rocket: Feature

As a user
I would like to be able to filter posts by their emotions
So that I can avoid certain emotional responses

### PR DESCRIPTION
**Pull request by Tirokk**
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-09-05T14:05:44Z" title="Thursday, September 5th 2019, 4:05:44 pm +02:00">Sep 5, 2019</time>_
_Merged <time datetime="2019-09-10T13:53:06Z" title="Tuesday, September 10th 2019, 3:53:06 pm +02:00">Sep 10, 2019</time>_
---

- Co-authored-by: Brent Vardy <brent.vardy@challengelogic.net>
- Co-authored-by: Mike Aono <aonomike@gmail.com>
- Co-authored-by: Harald <harald.reingruber@gmx.at>
@Tirokk was there as well
### Issues

- fixes #1488

### CODE REVIEW

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-09-10T13:53:01Z" title="Tuesday, September 10th 2019, 3:53:01 pm +02:00">Sep 10, 2019</time>_

---


Exactly 10 files changed. That's the threshold. I'll merge!

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-09-10T13:54:19Z" title="Tuesday, September 10th 2019, 3:54:19 pm +02:00">Sep 10, 2019</time>_

---


Thank you Harald (what's your Github name?) and @aonomike and @vardyb and @Tirokk  ! We :heart: you!

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-09-10T15:33:03Z" title="Tuesday, September 10th 2019, 5:33:03 pm +02:00">Sep 10, 2019</time>_

---


yes, that's right... we have a positive emotions filter for now... 
I also don't like the naming `GeneralFilterItems` as it' too general :rofl: 
Do you have a suggestion of a better naming convention? `There are only two hard things in Computer Science: cache invalidation and naming things.`

**Review by Mogge — APPROVED** [review]
fantastic

I have nothing to complain about this PR that would keep it from being merged! Great work!

The only thing I ask myself: I guess Dennis wanted to have a negative filter: If I deselect an emotion, there should be no posts with the deselected emotion. Right now, I guess we have a positive filter: If I select an emotion, every post must have the emotion. Am I right? @mattwr18 

I would say let's keep this behaviour. There might be performance issues, because it's always more expensive to search for sth. that is not there instead of searching for sth. that is.

Also the naming "GeneralFilterItems" is not very obvious to me.

**Pull request closed without merging**
