### PR TITLE
Add thumbor service

### PR DESCRIPTION
**Pull request by Tirokk**
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-05-18T11:56:45Z" title="Saturday, May 18th 2019, 1:56:45 pm +02:00">May 18, 2019</time>_
_Closed <time datetime="2019-06-14T20:21:08Z" title="Friday, June 14th 2019, 10:21:08 pm +02:00">Jun 14, 2019</time>_
---

This is my birthday present to @mattwr18. Feel free to merge this in
your PR unless you think this extends the scope of the PR.

Happy Birthday

Yet, I don't know how to send the returned URL of the image (it's in the
response header) to the backend.

Either this
1. webapp <---> thumbor
2. webapp <---> backend

Or this
1. webapp <---> backend
2. backend <---> thumbor

### Issues

- [X] None

### Checklist

- [X] None

### How2Test

- [X] None

### Todo

- [X] None

### CODE REVIEW

**Comment by Tirokk** [comment]
> [codecov[bot]](https://github.com/apps/codecov) **Authored by [codecov[bot]](https://github.com/apps/codecov)**
_<time datetime="2019-05-18T12:29:14Z" title="Saturday, May 18th 2019, 2:29:14 pm +02:00">May 18, 2019</time>_

---


# [Codecov](https://codecov.io/gh/Human-Connection/Human-Connection/pull/624?src=pr&el=h1) Report
> Merging [#624](https://codecov.io/gh/Human-Connection/Human-Connection/pull/624?src=pr&el=desc) into [399-user-profile-image-uploads](https://codecov.io/gh/Human-Connection/Human-Connection/commit/03bf8fb3d56998a8445c814bdceefe7f33865b30?src=pr&el=desc) will **not change** coverage.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/Human-Connection/Human-Connection/pull/624?src=pr&el=tree)

```diff
@@                       Coverage Diff                       @@
##           399-user-profile-image-uploads     #624   +/-   ##
===============================================================
  Coverage                           20.21%   20.21%           
===============================================================
  Files                                 158      158           
  Lines                                2227     2227           
  Branches                              107      107           
===============================================================
  Hits                                  450      450           
  Misses                               1753     1753           
  Partials                               24       24
```


| [Impacted Files](https://codecov.io/gh/Human-Connection/Human-Connection/pull/624?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [webapp/components/Upload/index.vue](https://codecov.io/gh/Human-Connection/Human-Connection/pull/624/diff?src=pr&el=tree#diff-d2ViYXBwL2NvbXBvbmVudHMvVXBsb2FkL2luZGV4LnZ1ZQ==) | `29.41% <ø> (ø)` | :arrow_up: |

**Comment by Tirokk** [comment]
> [ulfgebhardt](https://github.com/ulfgebhardt) **Authored by [ulfgebhardt](https://github.com/ulfgebhardt)**
_<time datetime="2019-05-19T01:49:53Z" title="Sunday, May 19th 2019, 3:49:53 am +02:00">May 19, 2019</time>_

---


@roschaefer I prefer the second suggestion (out of the suggested)

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-05-20T12:12:06Z" title="Monday, May 20th 2019, 2:12:06 pm +02:00">May 20, 2019</time>_

---


great @roschaefer, I'll have a look at this today... I saw you had suggested this, but haven't given it a try yet.

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-06-14T20:21:08Z" title="Friday, June 14th 2019, 10:21:08 pm +02:00">Jun 14, 2019</time>_

---


Agreed this would be closed for now @roschaefer 
Although, I am interested to see if this might help down the road

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-06-14T20:21:08Z" title="Friday, June 14th 2019, 10:21:08 pm +02:00">Jun 14, 2019</time>_

---


Agreed this would be closed for now @roschaefer 
Although, I am interested to see if this might help down the road

**Review by Mogge — APPROVED** [review]

**Pull request closed without merging**
