### PR TITLE
Revert tiptap upgrade

### LINKED ISSUE #572: Tiptap bug for 1.8.0
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-05-08T15:08:11Z" title="Wednesday, May 8th 2019, 5:08:11 pm +02:00">May 8, 2019</time>_
_Closed <time datetime="2019-05-09T16:27:10Z" title="Thursday, May 9th 2019, 6:27:10 pm +02:00">May 9, 2019</time>_
---

## :bug: Bugreport

upgrading tiptap introduces a bug, which has been reported here https://github.com/scrumpy/tiptap/issues/188

let's downgrade and follow the discussion there

### Steps to reproduce the behavior
1. $ cd `/webapp`
2.  run the tests with the `yarn test`

### Expected behavior

we should be able to have tests that interact with tiptap editor

### PR DESCRIPTION
**Pull request by Tirokk**
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-05-08T15:30:43Z" title="Wednesday, May 8th 2019, 5:30:43 pm +02:00">May 8, 2019</time>_
_Merged <time datetime="2019-05-09T16:27:10Z" title="Thursday, May 9th 2019, 6:27:10 pm +02:00">May 9, 2019</time>_
---

- it introduced a bug that caused failing tests
- I have found an open issue on the repo and commented what I experienced here https://github.com/scrumpy/tiptap/issues/188#issuecomment-490532736

### Issues

- fixes #572

### CODE REVIEW

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-05-08T15:34:52Z" title="Wednesday, May 8th 2019, 5:34:52 pm +02:00">May 8, 2019</time>_

---


@roschaefer to downgrade it successfully, I needed(?) to run `rm yarn.lock`, but I know you had told me there is a better way to do this. 

I think in that context what I had done was to run `git checkout origin/master -- yarn.lock`, but in this context since the `yarn.lock` had a newer version it wasn't downgrading it.

The way I did it however has caused upgrades to several packages not covered in this `PR`, so if you have a better idea how I can just downgrade `tiptap` and `tiptap-extensions` in the yarn.lock, I can fix this `PR` and push it back up

**Comment by Tirokk** [comment]
> [codecov[bot]](https://github.com/apps/codecov) **Authored by [codecov[bot]](https://github.com/apps/codecov)**
_<time datetime="2019-05-08T23:00:08Z" title="Thursday, May 9th 2019, 1:00:08 am +02:00">May 9, 2019</time>_

---


# [Codecov](https://codecov.io/gh/Human-Connection/Human-Connection/pull/575?src=pr&el=h1) Report
> Merging [#575](https://codecov.io/gh/Human-Connection/Human-Connection/pull/575?src=pr&el=desc) into [master](https://codecov.io/gh/Human-Connection/Human-Connection/commit/d6f423d845d6f44c553e768a31431afc7ce3d710?src=pr&el=desc) will **not change** coverage.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/Human-Connection/Human-Connection/pull/575?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##           master     #575   +/-   ##
=======================================
  Coverage   16.79%   16.79%           
=======================================
  Files         154      154           
  Lines        2138     2138           
  Branches       92       92           
=======================================
  Hits          359      359           
  Misses       1759     1759           
  Partials       20       20
```

**Comment by Tirokk** [comment]
> [codecov[bot]](https://github.com/apps/codecov) **Authored by [codecov[bot]](https://github.com/apps/codecov)**
_<time datetime="2019-05-08T23:00:08Z" title="Thursday, May 9th 2019, 1:00:08 am +02:00">May 9, 2019</time>_

---


# [Codecov](https://codecov.io/gh/Human-Connection/Human-Connection/pull/575?src=pr&el=h1) Report
> Merging [#575](https://codecov.io/gh/Human-Connection/Human-Connection/pull/575?src=pr&el=desc) into [master](https://codecov.io/gh/Human-Connection/Human-Connection/commit/d6f423d845d6f44c553e768a31431afc7ce3d710?src=pr&el=desc) will **not change** coverage.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/Human-Connection/Human-Connection/pull/575?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##           master     #575   +/-   ##
=======================================
  Coverage   16.79%   16.79%           
=======================================
  Files         154      154           
  Lines        2138     2138           
  Branches       92       92           
=======================================
  Hits          359      359           
  Misses       1759     1759           
  Partials       20       20
```

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-05-08T23:13:49Z" title="Thursday, May 9th 2019, 1:13:49 am +02:00">May 9, 2019</time>_

---


@mattwr18 no, I don't know a better way of downgrading an npm package. I would say `rm yarn.lock` is just fine.

I mean: It should work, right? In an ideal world, transitive dependencies should not have any effect :laughing:

**Review by Mogge — APPROVED** [review]

**Pull request closed without merging**
