### PR TITLE
🍰 feat(webapp): Display deployed version in footer

### LINKED ISSUE #1831: 🚀 [Feature] Used Release Version Number
> [proofy](https://github.com/proofy) **Authored by [proofy](https://github.com/proofy)**
_<time datetime="2019-10-07T21:17:10Z" title="Monday, October 7th 2019, 11:17:10 pm +02:00">Oct 7, 2019</time>_
_Closed <time datetime="2020-01-16T20:38:50Z" title="Thursday, January 16th 2020, 9:38:50 pm +01:00">Jan 16, 2020</time>_
---

## :rocket: Feature
I would like to see the version/release number of the hc software.

### Design & Layout
e.g. in the footer :
HC Version 1.03

### PR DESCRIPTION
**Pull request by Tirokk**
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2020-01-12T22:08:55Z" title="Sunday, January 12th 2020, 11:08:55 pm +01:00">Jan 12, 2020</time>_
_Merged <time datetime="2020-01-16T20:38:50Z" title="Thursday, January 16th 2020, 9:38:50 pm +01:00">Jan 16, 2020</time>_
---

## 🍰 Pullrequest

See #1831 this should help all our testers to see and compare the different deployed versions.

### Issues
- close #1831

### CODE REVIEW

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-01-12T23:36:37Z" title="Monday, January 13th 2020, 12:36:37 am +01:00">Jan 13, 2020</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/4106/specs"></a> <b title="Passed">51</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/4106/failures"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | fc051f22dc |
| **Started** | Jan 16, 2020 8:17 PM |
| **Ended** | Jan 16, 2020 8:29 PM |
| **Duration** | 12:05 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Chromium 79  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/4106/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings)

**Comment by Tirokk** [comment]
> [alina-beck](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2020-01-14T10:11:29Z" title="Tuesday, January 14th 2020, 11:11:29 am +01:00">Jan 14, 2020</time>_

---


How about we replace `Changes` with the version number and link to the Github releases from there? :grin:

**Comment by Tirokk** [comment]
> [datenbrei](https://github.com/datenbrei) **Authored by [datenbrei](https://github.com/datenbrei)**
_<time datetime="2020-01-14T13:02:29Z" title="Tuesday, January 14th 2020, 2:02:29 pm +01:00">Jan 14, 2020</time>_

---


@alina-beck  For me it sounds like a good idea.

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2020-01-16T18:15:46Z" title="Thursday, January 16th 2020, 7:15:46 pm +01:00">Jan 16, 2020</time>_

---


@mattwr18 I didn't disable the auto-commit in `yarn run release` because it would also disable the auto-tagging. I think we should avoid human errors here, so I left it as it was.

**Review by Mogge — APPROVED** [review]

**Pull request closed without merging**
