### PR TITLE
Remove duplicate pinned post record

### LINKED ISSUE #2022: 🐛 [Bug] Pinned Post appears twice on page
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-10-24T07:57:07Z" title="Thursday, October 24th 2019, 9:57:07 am +02:00">Oct 24, 2019</time>_
_Closed <time datetime="2019-10-24T09:24:16Z" title="Thursday, October 24th 2019, 11:24:16 am +02:00">Oct 24, 2019</time>_
---

## :bug: Bugreport

Once where it is supposed to, and once where it would be ordered by the createdAt date

### Steps to reproduce the behavior
1. go to the site 
2. pin a post, if you are an admin, if not there must be a pinned post to replicate the bug
3. make note of the time and title of the pinned post
4. scroll down till you see it a second time
5. Profit

### Expected behavior

Screenshot from 2019-10-23 23-55-58

### PR DESCRIPTION
**Pull request by Tirokk**
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-10-24T08:01:24Z" title="Thursday, October 24th 2019, 10:01:24 am +02:00">Oct 24, 2019</time>_
_Merged <time datetime="2019-10-24T09:24:16Z" title="Thursday, October 24th 2019, 11:24:16 am +02:00">Oct 24, 2019</time>_
---

- Maintain consistent orderBy for fetchMore

### Issues

- fixes #2022

### CODE REVIEW

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-10-24T08:16:05Z" title="Thursday, October 24th 2019, 10:16:05 am +02:00">Oct 24, 2019</time>_

---


Do we loose the pinned post feature through this? Don't we stop ordering the pinned post at the first position with this?

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-10-24T08:27:50Z" title="Thursday, October 24th 2019, 10:27:50 am +02:00">Oct 24, 2019</time>_

---


no @roschaefer, we maintain the pinned post, and remove duplicate records when fetchMore is called

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-10-24T08:36:35Z" title="Thursday, October 24th 2019, 10:36:35 am +02:00">Oct 24, 2019</time>_

---


OK, `fetchMore`. Still I don't understand why the pinned post appears again. It shouldn't matter if you order by the `pinned` attribute on pages > 1.

So here is my problem:

1. On the first page, you order by `pinned` and `createdAt` and get posts at index 0..11 with 0 being the pinned post
2. On the next page you order by `createdAt` and get the posts 12..23. Post at index 0 was the pinned post in step 1 but instead the post formerly at index 1 gets shifted to index 0.
3. What about the post at index 11? Do we miss it?

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-10-24T09:06:24Z" title="Thursday, October 24th 2019, 11:06:24 am +02:00">Oct 24, 2019</time>_

---


no @roschaefer, we don't lose any `Post`s

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-10-24T09:15:57Z" title="Thursday, October 24th 2019, 11:15:57 am +02:00">Oct 24, 2019</time>_

---


I'm so stupid. I mistook green for red :woman_facepalming:

**Review by Mogge — APPROVED** [review]
facepalm

Of course this makes a lot of sense.

**Pull request closed without merging**
