### PR TITLE
2019/kw15/hide_all_unfuctional_content

### PR DESCRIPTION
**Pull request by Tirokk**
> [ulfgebhardt](https://github.com/ulfgebhardt) **Authored by [ulfgebhardt](https://github.com/ulfgebhardt)**
_<time datetime="2019-04-08T08:50:39Z" title="Monday, April 8th 2019, 10:50:39 am +02:00">Apr 8, 2019</time>_
_Merged <time datetime="2019-04-10T12:17:59Z" title="Wednesday, April 10th 2019, 2:17:59 pm +02:00">Apr 10, 2019</time>_
---

## Pullrequest

hide all unfunctional content - fixes https://github.com/Human-Connection/Human-Connection/issues/429

### Issues

- [X] fixes https://github.com/Human-Connection/Human-Connection/issues/429
- [X] fixes https://github.com/Human-Connection/Human-Connection/issues/386

### Checklist

- [X] None

### How2Test

- [X] None

### Todo

- [X] None

### CODE REVIEW

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-04-08T10:52:28Z" title="Monday, April 8th 2019, 12:52:28 pm +02:00">Apr 8, 2019</time>_

---


@ulfgebhardt also mind that the build server prints a lot of linter warnings: https://travis-ci.com/Human-Connection/Human-Connection/builds/107424381

**Comment by Tirokk** [comment]
> [ulfgebhardt](https://github.com/ulfgebhardt) **Authored by [ulfgebhardt](https://github.com/ulfgebhardt)**
_<time datetime="2019-04-09T09:12:38Z" title="Tuesday, April 9th 2019, 11:12:38 am +02:00">Apr 9, 2019</time>_

---


@roschaefer fixed the lints -> i think it is best practice to just show fully implemented stuff. Therefor I cleaned all UIs of the placeholders.

Regarding incentive - I made issues just for that -> The Issues describe with graphics what needs to be implemented.

**Comment by Tirokk** [comment]
> [ulfgebhardt](https://github.com/ulfgebhardt) **Authored by [ulfgebhardt](https://github.com/ulfgebhardt)**
_<time datetime="2019-04-09T09:12:38Z" title="Tuesday, April 9th 2019, 11:12:38 am +02:00">Apr 9, 2019</time>_

---


@roschaefer fixed the lints -> i think it is best practice to just show fully implemented stuff. Therefor I cleaned all UIs of the placeholders.

Regarding incentive - I made issues just for that -> The Issues describe with graphics what needs to be implemented.

**Comment by Tirokk** [comment]
> [ulfgebhardt](https://github.com/ulfgebhardt) **Authored by [ulfgebhardt](https://github.com/ulfgebhardt)**
_<time datetime="2019-04-10T08:11:47Z" title="Wednesday, April 10th 2019, 10:11:47 am +02:00">Apr 10, 2019</time>_

---


I think we should not throw away stuff already created - just dont show it.
Github has problems showing the html commented out code properly, but thats just a few lines...

**Review by Mogge — CHANGES_REQUESTED** [review]
Can you just remove it altogether @ulfgebhardt ? Github does not even display the commented code as commented out.

**Review by Mogge — APPROVED** [review]

**Pull request closed without merging**
