### PR TITLE
[WIP] i18n-RU translations improvements

### PR DESCRIPTION
**Pull request by Tirokk**
> [vbelolapotkov](https://github.com/vbelolapotkov) **Authored by [vbelolapotkov](https://github.com/vbelolapotkov)**
_<time datetime="2019-11-12T07:45:31Z" title="Tuesday, November 12th 2019, 8:45:31 am +01:00">Nov 12, 2019</time>_
_Closed <time datetime="2019-11-21T13:04:40Z" title="Thursday, November 21st 2019, 2:04:40 pm +01:00">Nov 21, 2019</time>_
---

## 🍰 Pullrequest
Improvements to russian translations

Note: plurals for Russian locale accept three forms.
https://github.com/dkfbasel/vuex-i18n/blob/master/src/vuex-i18n-plurals.js#L73

### Issues
- None

### Todo
- [] Check other sections

### CODE REVIEW

**Comment by Tirokk** [comment]
> [vbelolapotkov](https://github.com/vbelolapotkov) **Authored by [vbelolapotkov](https://github.com/vbelolapotkov)**
_<time datetime="2019-11-12T07:46:53Z" title="Tuesday, November 12th 2019, 8:46:53 am +01:00">Nov 12, 2019</time>_

---


@ewanold fyi, I've created one more PR to add improvements for RU locale. It's still in progress, but feel free to check and ask questions if any.

**Comment by Tirokk** [comment]
> [vbelolapotkov](https://github.com/vbelolapotkov) **Authored by [vbelolapotkov](https://github.com/vbelolapotkov)**
_<time datetime="2019-11-15T12:17:47Z" title="Friday, November 15th 2019, 1:17:47 pm +01:00">Nov 15, 2019</time>_

---


@roschaefer, thanks for approval and nice gif 😀 I appreciate your trust as well 🙂, however, the PR is still in progress. I'll remove the [WIP] prefix and ask @ewanold for feedback before final review. What do you think?

**Comment by Tirokk** [comment]
> [ewanold](https://github.com/ewanold) **Authored by [ewanold](https://github.com/ewanold)**
_<time datetime="2019-11-15T18:46:11Z" title="Friday, November 15th 2019, 7:46:11 pm +01:00">Nov 15, 2019</time>_

---


@roschaefer I will post a 5-minute intro into the Russian alphabet as soon as Russian is available on HC :-)  then everything will be clear... at least you might be surprised how similar those 2 languages can be.

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-11-18T21:29:33Z" title="Monday, November 18th 2019, 10:29:33 pm +01:00">Nov 18, 2019</time>_

---


@vbelolapotkov @ewanold could you merge this when it's ready? It will pull in your changes into lokalise as well and that might save us from doing things twice.

**Comment by Tirokk** [comment]
> [vbelolapotkov](https://github.com/vbelolapotkov) **Authored by [vbelolapotkov](https://github.com/vbelolapotkov)**
_<time datetime="2019-11-19T04:09:24Z" title="Tuesday, November 19th 2019, 5:09:24 am +01:00">Nov 19, 2019</time>_

---


@roschaefer sure, will do! It should be ready soon. Just several sections left.

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2019-11-19T04:19:37Z" title="Tuesday, November 19th 2019, 5:19:37 am +01:00">Nov 19, 2019</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/#/projects/qa7fe2/runs/2176/specs"></a> <b title="Passed">48</b>  &bull; <a href="https://dashboard.cypress.io/#/projects/qa7fe2/runs/2176/failures"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | 7e9e641110 |
| **Started** | Nov 19, 2019 4:07 AM |
| **Ended** | Nov 19, 2019 4:19 AM |
| **Duration** | 12:32 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Chromium 78  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/#/projects/qa7fe2/runs/2176/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/#/projects/qa7fe2/settings)

**Comment by Tirokk** [comment]
> [Mogge](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2019-11-20T12:12:59Z" title="Wednesday, November 20th 2019, 1:12:59 pm +01:00">Nov 20, 2019</time>_

---


See #2305 . I think we can close this PR

**Comment by Tirokk** [comment]
> [vbelolapotkov](https://github.com/vbelolapotkov) **Authored by [vbelolapotkov](https://github.com/vbelolapotkov)**
_<time datetime="2019-11-21T14:02:13Z" title="Thursday, November 21st 2019, 3:02:13 pm +01:00">Nov 21, 2019</time>_

---


@Mogge could you please tell me why is it closed? I've just finished the updates and wanted to merge them.
@ewanold  could you please take a look at the overall changes?

**Review by Mogge — APPROVED** [review]
shrug

I don't speak Russian I cannot review this PR properly, can we merge it? I just trust you @vbelolapotkov

**Pull request closed without merging**
