### PR TITLE
fix(build): make locations spec more resilient

### PR DESCRIPTION
**Pull request by Tirokk**
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2020-03-23T19:53:18Z" title="Monday, March 23rd 2020, 8:53:18 pm +01:00">Mar 23, 2020</time>_
_Merged <time datetime="2020-03-24T08:38:22Z" title="Tuesday, March 24th 2020, 9:38:22 am +01:00">Mar 24, 2020</time>_
---

## 🍰 Pullrequest

Fixes build... do not hard code the id's as they are subject to change from `mapbox`'s side.
it is enough that the ids contain either `place`, `region`, `country`
### Issues

- None

### Todo

- [X] None

### CODE REVIEW

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-03-23T20:30:33Z" title="Monday, March 23rd 2020, 9:30:33 pm +01:00">Mar 23, 2020</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/6334/specs"></a> <b title="Passed">66</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/6334/failures"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | 2c997b2d0a |
| **Started** | Mar 23, 2020 8:04 PM |
| **Ended** | Mar 23, 2020 8:30 PM |
| **Duration** | 25:42 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Firefox 68  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/6334/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings)

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-03-23T20:48:45Z" title="Monday, March 23rd 2020, 9:48:45 pm +01:00">Mar 23, 2020</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/6337/specs"></a> <b title="Passed">66</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/6337/failures"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | ad3b4e0eca <span style="cursor:help;" title="Your CI provider generated this commit by merging this branch into the target branch.">ℹ️</span> |
| **Started** | Mar 23, 2020 8:25 PM |
| **Ended** | Mar 23, 2020 8:48 PM |
| **Duration** | 23:05 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Firefox 68  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/6337/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings)

**Comment by Tirokk** [comment]
> [mattwr18](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2020-03-24T08:38:18Z" title="Tuesday, March 24th 2020, 9:38:18 am +01:00">Mar 24, 2020</time>_

---


> This surely does the trick. I am still asking myself how we suddenly receive different ids from mapbox.

yeah, I think that's strange, I wonder if this means that we are going to be creating multiple identical locations because the id's have changed :woman_shrugging:

**Review by Mogge — APPROVED** [review]
This surely does the trick. I am still asking myself how we suddenly receive different ids from mapbox.

**Pull request closed without merging**
